### ISSUE TITLE
Able to search out a password-protected files when not authenticated

### ISSUE THREAD

**Issue by bjrjk** [spencerwooo/onedrive-vercel-index#1014]
**Describe the bug**
When you are using searching function to find files, password-protected files can also be shown when users aren't authenticated.

**To Reproduce**
Assume you have a file "protected_file" in folder "private", which is password-protected but you are not authenticated:
1. Search "protected_file"
2. See your password-protected filename appear in the candidate file list appeared.

**Expected behavior**
The password-protected file should never appear in non-authenticated situation.

**Comment by spencerwooo** [comment]
Dup #733 and discussed in #735
