### ISSUE TITLE
500 - Internal server error

### ISSUE THREAD

**Issue by Tresillo2017** [spencerwooo/onedrive-vercel-index#1031]
**Describe the bug**
500: INTERNAL_SERVER_ERROR
Code: INTERNAL_FUNCTION_INVOCATION_FAILED
ID: cdg1::crzbm-1686686804561-b89909528173
**To Reproduce**
1. Go to 'your deployment url'
2. See error

**Expected behavior**
To load the webpage
**Screenshots**
![image](https://github.com/spencerwooo/onedrive-vercel-index/assets/56476330/4151d7bc-1ac7-46a9-b431-83b38ebda7de)
![image](https://github.com/spencerwooo/onedrive-vercel-index/assets/56476330/54a7f7d9-580b-437f-a028-c396e761d3bb)

**Additional context**

**Comment by Tresillo2017** [comment]
![image](https://github.com/spencerwooo/onedrive-vercel-index/assets/56476330/52d4912b-92d7-44c6-abf3-6a60102fa3e9)
Maybe it's because this

**Comment by crushedoreos** [comment]
I'm facing the same issue. Just wanted to check, are you using the template that includes [this commit](https://github.com/spencerwooo/onedrive-vercel-index/commit/eadb1c7d22364c358751367e8bedbe4854fae057)?

**Comment by Tresillo2017** [comment]
I synced my fork with the latest commits but since vercel's api isn't working it can't be build correctly. It's not the repo issue (although they are depreciating old versions of nextjs).
