### ISSUE TITLE
app 'd87bcc39-1750-4ca0-ad54-f8d0efbb2735' are expired

### ISSUE THREAD

**Issue by shirohako** [spencerwooo/onedrive-vercel-index#1051]
**Describe the bug**

Step 3/3: Get access and refresh tokens
粘贴 localhost://开头的地址后，提示

```
AADSTS7000222: The provided client secret keys for app 'd87bcc39-1750-4ca0-ad54-f8d0efbb2735' are expired. 
Visit the Azure portal to create new keys for your app: https://aka.ms/NewClientSecret, or consider using certificate credentials for added security: https://aka.ms/certCreds.
```

**To Reproduce**
1. Step 1/3: Preparations 
2. Step 2/3: Get authorisation code ,  open auth url and patse code
3. See error : Whoops, looks like we got a problem: invalid_client.

**Expected behavior**
N/A

**Comment by iRedScarf** [comment]
作者的clientId和clientSceret过期了

**Comment by L1468999760** [comment]
使用自己的clientId，就是完成教程中可选的那一步，亲测可行。
