### ISSUE TITLE
encodePath引入path末尾的`/`导致世纪互联Onedrive下无法获取目录

### ISSUE THREAD

**Issue by aidenlx** [spencerwooo/onedrive-vercel-index#109]
在当前版本[e53716](https://github.com/spencerwooo/onedrive-vercel-index/commit/e53716eb12dc6ab207247e0945e78db3b80517ac)下，以默认base配置（api.json->`  "base": "/Public",`）运行，[encodePath](https://github.com/spencerwooo/onedrive-vercel-index/blob/e53716eb12dc6ab207247e0945e78db3b80517ac/pages/api/index.ts#L10-L16)会以`/Public/`输出，导致发送的请求
```sh
curl --request GET \
  --url 'https://microsoftgraph.chinacloudapi.cn/v1.0/me/drive/root:/Public/:/children?select=%40microsoft.graph.downloadUrl%2Cname%2Csize%2Cid%2ClastModifiedDateTime%2Cfolder%2Cfile&top=100' \
  --header 'Authorization: Bearer ...'
```
返回404（`The resource could not be found.`）

而将[此行](https://github.com/spencerwooo/onedrive-vercel-index/blob/e53716eb12dc6ab207247e0945e78db3b80517ac/pages/api/index.ts#L15)改为
```ts
return `:${encodeURIComponent(encodedPath.replace(/\/$/, ""))}`
```
即可发送正确的请求，即：

```sh
curl --request GET \
  --url 'https://microsoftgraph.chinacloudapi.cn/v1.0/me/drive/root:/Public:/children?select=%40microsoft.graph.downloadUrl%2Cname%2Csize%2Cid%2ClastModifiedDateTime%2Cfolder%2Cfile&top=100' \
  --header 'Authorization: Bearer ...'
```

**Comment by spencerwooo** [comment]
Pull #105 seems to have fixed this. Thanks.
