### ISSUE TITLE
README.md 切换页面闪动

### ISSUE THREAD

**Issue by aozaki-kuro** [spencerwooo/onedrive-vercel-index#125]
之前修改useSWR选项后，主页到第一层文件夹的 README.md 在切换后不再闪动。

但是发现从第二层到第三层文件夹，再切换回第二层之后发现会闪动。
从更深层的文件夹往上一层切换也能复现出这个问题。
![1](https://user-images.githubusercontent.com/28428951/134521335-168b5c62-083d-4090-93c6-b2fc9c3174e3.gif)

但是从第三层以及更深文件夹直接回主页不会闪动。

感觉是个bug，希望可以再排查一下😂

**Comment by spencerwooo** [comment]
在 8a5f4482cd109b41687e6f683669af1c6366397a 之后 `useSWR` 的默认行为变成第一次有 cache 加载，后续不 revalidate，如果页面强刷新或重新联网才会自动 revalidate。其余行为……说实话我也不知道了，暂时是不太好解决，我只能后面看情况如果真的发现有问题才能「修」了。

**Comment by spencerwooo** [comment]
我着实觉得这个修好了，我重写了后面预览文件的时候把文件内容 GET 下来的逻辑（用了一个 custom hook），这样一个页面只出现一个 useSWR，就应该不会有两个 useSWR 互相触发导致 cache 互相失效需要重新载入的刷新问题了。但愿修好了……

**Comment by aozaki-kuro** [comment]
感谢，目前在您的部署页面上测试通过了…晚些我到家重新部署一下我这里的项目看看
