### ISSUE TITLE
Feature request: Folder and batch download

### ISSUE THREAD

**Issue by spencerwooo** [spencerwooo/onedrive-vercel-index#143]
### Discussed in https://github.com/spencerwooo/onedrive-vercel-index/discussions/136

<div type='discussions-op-text'>

<sup>Originally posted by **myl7** October  7, 2021</sup>
onedrive-vercel-index has preview support for many file formats, which encourages webmasters to serve the shared files in bulk other than in zip, making preview of the files possible.
However, onedrive API doesnot provide a way to download a folder or download files in batches. You actually *can* do them via onedrive share url, and onedrive just doesnot provide the api.
The fact makes visitors difficult to download the files stored (even hierarchically) in a folder.
To solve it and enhance the experience, I have come up with some solutions:

1. ... just paste an onedrive share url in the index page. Users can go to the onedrive share page to download anything they want. No code change required.
2. Provide a button to let the user download (even recursively) all items in the page. Seems not hard.
3. Provide a button to copy all download urls in the page, and ask the user to use other tools to download these files. Even easier than 2.
4. Provide a button to send all download urls to a paticular server, and the server fetches the files, zips them, and sends the zip files back to the user in stream. This additionally requires another backend project and makes onedrive-vercel-index not so serverless.
5.  Fetch the files, zip them, and download the zip files in stream, but in client side, in browser js. I am not sure if this is possible. But this will be the most comfortable solution for users.

Currently I would support 1 & 2.</div>

-> Let's see what we can do about this.

**Comment by shoucandanghehe** [comment]
I like 2, which is exactly what I want

**Comment by spencerwooo** [comment]
Closing this with the landing of #177 and #169
