### ISSUE TITLE
嘤嘤嘤不会搭建有没有完整教程

### ISSUE THREAD

**Issue by QuantumEdgeCode** [spencerwooo/onedrive-vercel-index#178]
#    @@@嘤嘤嘤不会搭建有没有完整教程 #

**Comment by qkqpttgf** [comment]
有啊，在readme里。

或者，来用我的OneManager，安装简单。

**Comment by spencerwooo** [comment]
Refer to https://github.com/spencerwooo/onedrive-vercel-index/issues/72#issuecomment-909282228 for now
