### ISSUE TITLE
请问如何修改文件夹图标啊

### ISSUE THREAD

**Issue by m1omoe** [spencerwooo/onedrive-vercel-index#189]
感谢大佬的辛勤工作，看到大佬的文件夹都有自定义的图标 看了所有的issues没有关于这个的才愚笨的发问

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by myl7** [comment]
参考 https://github.com/spencerwooo/onedrive-cf-index#%EF%B8%8F-folder-indexing `Emoji as folder icon when available (if the first character of the folder name is an emoji).` 在文件夹名字前加一个 emoji 即可。
如需自定义复杂的图标，就得改代码了。

**Comment by m1omoe** [comment]
谢谢谢谢
