### ISSUE TITLE
ACCESS_TOKEN on Vercel exceeds 4KB

### ISSUE THREAD

**Issue by asagichan** [spencerwooo/onedrive-vercel-index#195]
![image](https://user-images.githubusercontent.com/46355728/147422086-29260acd-75e7-44af-af32-ff54cbbc197b.png)

its say exceeds 4KB, i cant input the access token

**Comment by myl7** [comment]
Duplicated with #19 , though it is in different language. But there is English translation in it to tell how to solve the problem.

One possible solution is to put your envs in a file `.env.local` in the project root with content like:

```
A=aaaaaaaaa
B=bbbbbbbbb
```

And add it to the repo (by default it is ignored, edit `.gitignore` to unignore it).

Or you may put the envs in `config/api.json` and change code in `pages/api/index.ts` to load access token and other stuff from the json file.

**Comment by jhonnyminedr** [comment]
hey,
[GET] /api?path=/
13:01:31:67
Function Status:
None
Edge Status:
500
Duration:
1481.43 ms
Init Duration:
488.26 ms
Memory Used:
79 MB
ID:
qg6c6-1640590291646-1902a9aa0797
User Agent:
Vercelbot/0.1 (+https://vercel.com)
_token=0.AXEAhUQpsSWULUSnd3BQvtybttllVrGm7ZJAhTkO7Ddq_VlxABc.AgABAAAAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P_nmcsgAULne6y5aalyKuObYUY2zKElpZqq8rSY_ZsfeZdNCvAF4NmkxhXIFFy_W2bCBhYEHUBiHCF2LRrp9_N_jTNBcQvXJUzqilyoyjUr-LU2Uq5WiDURiPUrGdIvMOp4kXbC_ygKFDg6LpPgM0PU5yTr8KEJr-qEfLPBr03_LjFOj_V2FFYvhmyL2ynuHu8uAcghFWfuR_07Ckwftq_RMi0jFkr8ZOb-oUg3muyaTDfER1dAA7OhN74TFK09mA4oYOttWdZjSeom69SvV9UeFxiqMrWcoAXtUBCJ6PMy2dmwHfYNDTXUIcSBHbixPvtWhePGEoHbiffYStAy08PMLkLv07Gx_BwUZqQBEAaFkdFK9FqBJl5ZrPCdvFTK6lI52sN027lViusFxcfA0lNKO_iLRRQ1sQpKddSAv8pdcMWAfKc98ao14pCwpHaOy_FeKKXZtUqQ8Sak_ICwMZuP3soiVnSEU2RWEP1xKz4NkHKg2860Q0V2C_MHMRkLxaSdk5XICWvOKNMwGAZisi01WDkBOtntA2WbEgM8xV4wsaYvMBODoeWF9JvzntfgmLuuvO8OW16xzPSizbGfaXJ9ablXvdoh6wN58cQAUP9G5jdurV6Gs2x5nXR0TMfYbA3dcT2Lt134Q7iHgJEi2Pv5O_X6mRP8a6kBVDZqXaU29_es1Hap4Ew1t75KddPrA9oTp8mmB8bmZIJ-R9DNjMbC04S8cqOv9HF9eHmb4V3iIloOi_tWbHQgDhGHzdKDdgtghp2v2SW2RMxiTd4Kas42GKQDqeFBqkxEGPHveswSyr0nbB82pYdSodNKdE3U0vWLIA8nmfpjsstgdAyzY-fg_ABVxevlhQnzlQaJyin8WVxX8nlGx4U6jpyje2UWRTs6sUulQGzJDDQKzlzJ77X3YEj2VNe4AR0&grant_type=refresh_token',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      transitional: [Object]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /common/oauth2/v2.0/token HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/x-www-form-urlencoded\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Content-Length: 1198\r\n' +
        'Host: login.microsoftonline.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/common/oauth2/v2.0/token',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'login.microsoftonline.com',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: {
      error: 'invalid_client',
      error_description: 'AADSTS7000215: Invalid client secret is provided.\r\n' +
        'Trace ID: 2418178b-3349-4be3-bbd8-52703882c800\r\n' +
        'Correlation ID: 8e89d318-24b4-4bed-b0cc-ba07f32d8350\r\n' +
        'Timestamp: 2021-12-27 07:31:33Z',
      error_codes: [Array],
      timestamp: '2021-12-27 07:31:33Z',
      trace_id: '2418178b-3349-4be3-bbd8-52703882c800',
      correlation_id: '8e89d318-24b4-4bed-b0cc-ba07f32d8350',
      error_uri: 'https://login.microsoftonline.com/error?code=7000215'
    }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
RequestId: 496dbc6c-3b16-405c-87b6-18a4ad1dbac2 Error: Runtime exited with error: exit status 1
Runtime.ExitError

whats the issue

**Comment by spencerwooo** [comment]
Fixed by PR #210
