### ISSUE TITLE
Office 无法预览

### ISSUE THREAD

**Issue by hmsjy2017** [spencerwooo/onedrive-vercel-index#21]
Office 无法预览，其他正常。
![E9204331-BB60-485E-B022-6D8C48D56BA2](https://user-images.githubusercontent.com/42692274/125437778-21a62d40-a1e5-4941-a3fc-67ad83f6938f.png)
![56B3D1A6-4F9B-42E5-926F-A956DFF38AD0](https://user-images.githubusercontent.com/42692274/125437783-a5a52571-c4e8-45bf-aaf4-81f896daa674.png)

**Comment by spencerwooo** [comment]
应该是你的 OneDrive 文件分享的设置问题？报错信息是 document not publicly accessible。

**Comment by hmsjy2017** [comment]
@spencerwooo 怎么设置？生成分享链接还是不行
![733B4A0F-110F-449A-B78D-5982BD08728D](https://user-images.githubusercontent.com/42692274/125539300-7cdc81e3-8bc8-4d42-823b-8689fdb9329e.png)
![F7F9AE09-9432-41EE-94E9-9FF475F9BF16](https://user-images.githubusercontent.com/42692274/125539348-f923158b-21f0-48d8-b43f-8beccce774a3.png)

**Comment by spencerwooo** [comment]
hmmmm，你这 SharePoint，我有点怀疑是这个问题。Office 预览使用的是 https://github.com/yatheeshraju/preview-office-docs，不知道有没有对 SharePoint 做支持

**Comment by chillgoor** [comment]
我也是同样的问题，测试了一下用FODI的oneindex同一个文件能预览，我也很奇怪
