### ISSUE TITLE
预览空白文本文件时，会一直显示`Loading file content...`

### ISSUE THREAD

**Issue by returnL** [spencerwooo/onedrive-vercel-index#217]
当文本文件内不包含内容时，会一直显示`Loading file content...`
如下图所示
![image](https://user-images.githubusercontent.com/44701395/147845334-8baea848-b358-4825-bbd0-51bc7c6d22d5.png)
![image](https://user-images.githubusercontent.com/44701395/147845335-80f05017-6a7c-4dac-89e3-317a7a84fab2.png)

**Comment by spencerwooo** [comment]
测试链接：https://drive.spencerwoo.com/%F0%9F%A5%9F%20Some%20test%20files/Previews/i%20am%20empty.txt

![image](https://user-images.githubusercontent.com/32114380/148389940-6a38eee6-0b0b-480d-8645-5ed1f4dab655.png)
