### ISSUE TITLE
Link字段设为空时部署时报错

### ISSUE THREAD

**Issue by BrandonStudio** [spencerwooo/onedrive-vercel-index#218]
![如图所示](https://user-images.githubusercontent.com/55647556/147849797-764ac0aa-fe9d-42fd-8fba-b91228e036dc.png)

**Comment by spencerwooo** [comment]
暂时改一下 `Navbar.tsx` 里面吧，如果不需要链接的话把[那部分](https://github.com/spencerwooo/onedrive-vercel-index/blob/main/components/Navbar.tsx#L56-L67)全删掉就行，后面我在更新修复
