### ISSUE TITLE
自动刷新 Token

### ISSUE THREAD

**Issue by People-11** [spencerwooo/onedrive-vercel-index#22]
因为某些原因，我只能使用rclone来获取access_token以及refresh_token，但是这些token有效期仅为一个小时。
所以我有一个想法，用户需要Import此项目并设置为Private，将Client ID与Client Secret写入到项目的Secret中，然后通过GitHub Actions自动通过Secret刷新token并且把token push到Repo的配置文件中，同时Vercel通过新push的token重新部署。这样可以同时解决Vercel 4KB限制以及token过期的问题。

**Comment by People-11** [comment]
我观察到使用rclone获取的token有效期只有一小时，而另一个工具获取的有效期为一周。所以我想询问本项目是否会自动刷新token，而刷新间隔为多长时间？以选择合适的工具进行token获取。

**Comment by nfway** [comment]
> 我观察到使用rclone获取的token有效期只有一小时，而另一个工具获取的有效期为一周。所以我想询问本项目是否会自动刷新token，而刷新间隔为多长时间？以选择合适的工具进行token获取。

另一个工具是什么？

之前发现过一个 ：[heymind.github.io/tools/microsoft-graph-api-auth](https://heymind.github.io/tools/microsoft-graph-api-auth ) (没有验证)
 
以及：[FODI ](https://logi.im/fodi/get-code/) （没有验证）

**Comment by People-11** [comment]
> > 我观察到使用rclone获取的token有效期只有一小时，而另一个工具获取的有效期为一周。所以我想询问本项目是否会自动刷新token，而刷新间隔为多长时间？以选择合适的工具进行token获取。
> 
> 另一个工具是什么？
> 
> 之前发现过一个 ：[heymind.github.io/tools/microsoft-graph-api-auth](https://heymind.github.io/tools/microsoft-graph-api-auth) (没有验证)
> 
> 以及：[FODI ](https://logi.im/fodi/get-code/) （没有验证）

heymind的网站在我这里已经不能用了，无法获取token，FODI的话没试过，而且看上去有点简陋

**Comment by qkqpttgf** [comment]
> 因为某些原因，我只能使用rclone来获取access_token以及refresh_token，但是这些token有效期仅为一个小时。 所以我有一个想法，用户需要Import此项目并设置为Private，将Client ID与Client Secret写入到项目的Secret中，然后通过GitHub Actions自动通过Secret刷新token并且把token push到Repo的配置文件中，同时Vercel通过新push的token重新部署。这样可以同时解决Vercel 4KB限制以及token过期的问题。

有效期3599的是access token，refresh token是90d。
