### ISSUE TITLE
可否增加对.url链接的解析？

### ISSUE THREAD

**Issue by BrandonStudio** [spencerwooo/onedrive-vercel-index#221]
![image](https://user-images.githubusercontent.com/55647556/147851140-0efe9eb1-f8f7-40dc-9c57-5e29a1fc4640.png)
毕竟OneDrive原生支持
![image](https://user-images.githubusercontent.com/55647556/147851155-1ac660b3-b8c3-4450-99b9-79b94f048c87.png)

……或者，能不能添加一个切换打开方式的按钮？这样可以自己选择打开方式，#130 是不是也能这么解决？

**Comment by spencerwooo** [comment]
test here: https://drive.spencerwoo.com/%F0%9F%A5%9F%20Some%20test%20files/baidu.url
