### ISSUE TITLE
删除 "email" 字段后部署时报错

### ISSUE THREAD

**Issue by txyyh** [spencerwooo/onedrive-vercel-index#223]
![image](https://user-images.githubusercontent.com/41893946/147853084-c20c2f31-d1b5-4a77-a7dd-066a755758fa.png)

**Comment by spencerwooo** [comment]
原理同 #218，暂时先删掉那部分，后面我在更新修复

**Comment by spencerwooo** [comment]
leave the email field as

```json
{
  "email": "",
}
```

if you don't want to add an email.

**Comment by txyyh** [comment]
@spencerwooo 
![image](https://user-images.githubusercontent.com/41893946/147904836-345a1464-1597-4cea-9b54-116260bc6471.png)
