### ISSUE TITLE
文件夹列表读取最多只能到200项么？

### ISSUE THREAD

**Issue by nfway** [spencerwooo/onedrive-vercel-index#23]
谢谢作者做出这么棒又简单的作品。

昨天分别在 Vercel 和 Netlify 部署了，几个onedrive 中有个文件夹有 1000+文件，发现如下：

- Vercel 的单个文件夹里只能读取到197项 ；
- Netlify 的单个文件夹则能读取到200项（两个不同 onedrive 复现）。

请问如何能列表至1000或1000+ ？或者可能 [是这个 issue](https://github.com/spencerwooo/onedrive-vercel-index/issues/2) 提到。不过我这里可能单页列表的数量会更大……

感谢

**Comment by spencerwooo** [comment]
是这样的就是你提到的那个 issue，会实现的有生之年肯定会实现的 _(:з」∠)_
