### ISSUE TITLE
Proxied download doesn't work

### ISSUE THREAD

**Issue by heddxh** [spencerwooo/onedrive-vercel-index#248]
![Screenshot_20220109-170758](https://user-images.githubusercontent.com/63106571/148676162-ce2073fb-c9fb-43f8-82cf-ecb39e420446.png)
And I tired the demo,same problem.

**Comment by spencerwooo** [comment]
ok i see the problem, the `directLink` option used in `api.json` is set to only allow onedrive direct links, if not specified, the proxy could be used to relay any random link what-so-ever. i see that you are using sharepoint, so you can set that option to something like `https://nvzwjezr-my.sharepoint.com/`.

the reason why the demo site is also not working is that i thought all direct links start with

```
https://public.dm.files.1drv.com
```

but today it suddenly starts with

```
https://public.bn.files.1drv.com
```

should be fixed some time later.

**Comment by spencerwooo** [comment]
onedrive international users should be able to use this directly, sharepoint users need to change the regex matching the url in `directLinkRegex` defined in `api.json`.

**Comment by heddxh** [comment]
resolved. Thx!
