### ISSUE TITLE
请求增加对.mov格式的支持

### ISSUE THREAD

**Issue by W4J1e** [spencerwooo/onedrive-vercel-index#256]
感谢大佬的开源项目，速度很快，界面也很美观。但是上传视频后发现.MOV格式的视频无法在线预览，也就无法调用系统播放器播放，请求支持，非常感谢。

**Comment by spencerwooo** [comment]
verified: https://drive.spencerwoo.com/%F0%9F%A5%9F%20Some%20test%20files/Videos%20and%20music/file_example_MOV_1920_2_2MB.mov

**Comment by W4J1e** [comment]
wow，效率超高！非常感谢！

**Comment by W4J1e** [comment]
我刚刚拉取了更新部署之后才发现，可能应该是我手机录制的视频编码方式不一样，所以无法预览：
`https://pan.hin.cool/MusicVideo/Pentatonic%E5%8D%81%E5%91%A8%E5%B9%B4%E5%B7%A1%E6%BC%94%E9%87%8D%E5%BA%86%E3%80%8A%E8%8C%89%E3%80%8B.MOV`
我下次转码了再传上来吧，感谢您。

**Comment by spencerwooo** [comment]
不一定，也有可能是浏览器直接不支持你这个 `.mov` 文件播放，浏览器播放视频反正就是会有各种格式问题的
