### ISSUE TITLE
very hard steps to get token stuff for onedrive..... ;(

### ISSUE THREAD

**Issue by AmirulAndalib** [spencerwooo/onedrive-vercel-index#26]
hi there
# can you please provide use tutorial for getting refresh token access token for OD correctly i tried many times it doesnt work ....please help

**Comment by aozaki-kuro** [comment]
There is a very detailed version of token acquirement in the previous repo.
Please read [this](https://github.com/spencerwooo/onedrive-cf-index#generating-onedrive-api-tokens) .
Also consider using the [beetcb/ms-graph](https://github.com/beetcb/ms-graph-cli) to require the tokens.

**Comment by People-11** [comment]
> hi there
> 
> # can you please provide use tutorial for getting refresh token access token for OD correctly i tried many times it doesnt work ....please help

1. Install Node.js on your computer
2.  Run npx @beetcb/ms-graph-cli in the terminal or command line.
3.  Follow the steps to get the token
