### ISSUE TITLE
竖屏排版问题（小问题）

### ISSUE THREAD

**Issue by BrandonStudio** [spencerwooo/onedrive-vercel-index#297]
文件名过长时预览框中是否考虑对文件名换行显示？
![image](https://user-images.githubusercontent.com/55647556/150627129-684e6738-9f06-435e-b8de-fe5f28db5629.png)
（小问题，优先级极低）

**Comment by MCSeekeri** [comment]
竖屏还有一个问题需要解决
![image](https://user-images.githubusercontent.com/20928094/150997214-9b361007-9926-44f7-84f4-6f4d6255b0f2.png)
缩略图看起来很诡异，完全不能发挥"缩略"的作用
