### ISSUE TITLE
需要重新给予应用权限

### ISSUE THREAD

**Issue by qsgy-edge** [spencerwooo/onedrive-vercel-index#298]
我在使用管理员账号登录时忘记勾选为组织同意，之后登录会直接跳转host链接，无法再次授权，导致子用户无法使用，我该如何重新给予权限。

**Comment by BrandonStudio** [comment]
尝试访问 /onedrive-vercel-index-oauth/step-1 ？

**Comment by qsgy-edge** [comment]
我清理了浏览器数据与cookies后重新访问vercel.app还是直接跳转host，不会再次出现授权界面

**Comment by myl7** [comment]
试试连接你所提供的 redis 然后删掉上面的 `refresh_token` 和 `access_token` 两个 key 的数据
如果用的是 upstash 的话可以在网页管理面板里用 Data Browser 来删

**Comment by qsgy-edge** [comment]
Data Browser是空的，我的子用户无法登录显示需要管理员授权，用管理员账号登录时忘记勾选为组织同意，之后就登录不了了

**Comment by qsgy-edge** [comment]
这个授权数据应该是在微软的服务器，我想知道有没有办法取消授权再重新授权
