### ISSUE TITLE
Supporting search in SharePoint and OneDrive for Business deployments

### ISSUE THREAD

**Issue by spencerwooo** [spencerwooo/onedrive-vercel-index#299]
### Problem description:

The search we use leverage OneDrive Graph API, which, _to our surprise_, returns inconsistent results across different versions of OneDrive. The `path` field returned in `parentReference`, which we use to determine the route of the search result, is missing in sites including SharePoint versions of OneDrive. (And I suspect OneDrive for Education also would fail.)

Response in OneDrive international:

```jsonc
{
  // ...
  "parentReference": {
    "driveId": "ba63e0ea99dd98a3",
    "driveType": "personal",
    "id": "BA63E0EA99DD98A3!101",
    "path": "/drive/root:/Public/...images"
  }
}
```

Response in OneDrive for Business (or SharePoint):

```jsonc
{
  // ...
  "parentReference": {
   "driveId": "b!HHKxEe-tCUSO3uwES5r92kUCpw2Kc7ZOsvIWTv_MiTfm6fDv2B0pQrMbNCud5_8Q"
    "driveType": "business"
    "id": "01EYSPL6RHQBXPXWRLUVFYF5VWBO2QFEYF"
  }
}
```

### Tasks

- [x] Display a short error message for SharePoint users for now.
- [x] Find a valid API return that could be used to determine the route of search results.

**Comment by spencerwooo** [comment]
Still waiting for my own SharePoint to finish building its search index 😮‍💨, I still have nothing returned in my search results no matter what I search for. (As of 16:33 UTC+8, Jan.23, 2022)

**Comment by jinoo2005609** [comment]
Ahh, so that's why I couldn't get any search results from my vercel index.

**Comment by myl7** [comment]
Literally, though `parentReference` doesnot have `path` key for e5 developer subscriptions (surprisingly and sadly), one possible solution is to use the id returned in the api, then query the item information with the id, finally in the result of item query `parentReference` has `path` key. One example is available in my old searching support PR.

**Comment by myl7** [comment]
Ref https://github.com/spencerwooo/onedrive-vercel-index/pull/230/commits/f744d3973f09537de9677876c6c325cf6f343674

**Comment by spencerwooo** [comment]
It's not that I don't want to find a way to support OneDrive Business, it's that the search API does not return anything for me in my test OneDrive Business account - no matter what I search for.

![telegram-cloud-photo-size-5-6298397213067423503-y](https://user-images.githubusercontent.com/32114380/150729971-1158ab35-3e53-482e-844a-6e6d7e4fe4d7.jpg)

**Comment by myl7** [comment]
I would be willing to provide my e5 developer account, mounted on onedrive-vercel-index and having searching results, for you if you need it for testing right now. (Since it is already public.)

**Comment by spencerwooo** [comment]
oh my god it's working now...?? why!!?

![Screenshot 2022-01-24 at 15 39 35](https://user-images.githubusercontent.com/32114380/150741040-ed8f8ef9-97d7-42fd-a729-db76b5a99f8f.png)

**Comment by Micraow** [comment]
Mine is E5 account too. It can search files as soon as I install the onedrive-vercel-index, but its result is wrong, nothing to do with the words I enter. I have tried Chinese and English. And they have the same problem ...

share.pengs.top

**Comment by Micraow** [comment]
In addition, I notice it searches by requesting Microsoft API, not "native search"

**Comment by sridhar6564** [comment]
> In addition, I notice it searches by requesting Microsoft API, not "native search"

can i add the sharepoint in it
