### ISSUE TITLE
OneDrive API causes PDF.js web viewer failures

### ISSUE THREAD

**Issue by zkeq** [spencerwooo/onedrive-vercel-index#300]
`English is not my native language; please excuse typing errors.`

Problem description: a mobile phone or using firefox browser can't preview in PDF file.
问题描述: 手机端或使用火狐浏览器时在预览 pdf 文件时无法正常加载

~~Solution:  Delete PDF.Js validation of cross-domain source code commented~~
~~解决方案: 将 pdf.js 中验证跨域的相关代码注释掉..~~

#### For specific reasons, please see the discussion below.

Application of ready to work properly : https://pdf-for-onedrive.vercel.app/
正常工作的 pdf.js 代码:  https://pdf-for-onedrive.vercel.app/

### A viable solution

```
So just replace 
https://mozilla.github.io/pdf.js/web/viewer.html?file=
to  
https://pdf-for-onedrive.vercel.app/?file=
```
```
所以将 PDFPreview.tsx 文件中的
https://mozilla.github.io/pdf.js/web/viewer.html?file=
替换成 
https://pdf-for-onedrive.vercel.app/?file= 即可!
```
##### 测试链接:

[出错的链接](https://zkeq-onedrive.vercel.app/cpp.pdf) (使用火狐浏览器或手机访问时会出错) `https://mozilla.github.io/pdf.js/web/viewer.html?file=`

[修复后的链接](https://tuostudy.com/%F0%9F%93%9A%20060%23%20%E5%AD%A6%E4%B9%A0%E8%B5%84%E6%96%99/%F0%9F%93%81%2004%23%20%E7%89%A9%E7%90%86/%E5%88%9D%E4%B8%AD%E7%89%A9%E7%90%86%E6%9C%9F%E6%9C%AB%E5%A4%8D%E4%B9%A0%E5%A4%A7%E7%A4%BC%E5%8C%85/%E5%88%9D%E4%B8%89%E7%89%A9%E7%90%86%E4%B8%8A%E5%AD%A6%E6%9C%9F%E9%87%8D%E7%82%B9%E7%9F%A5%E8%AF%86%E7%82%B9%E6%80%BB%E7%BB%93.pdf) (均测试正常) `https://pdf-for-onedrive.vercel.app/?file=`

### 相关测试截图: 
Relevant test screenshot :

[![0.png](https://p18.qhimg.com/t01567e81e59fb49633.png)](https://p18.qhimg.com/t01567e81e59fb49633.png)

**Comment by spencerwooo** [comment]
pdf-for-onedrive.vercel.app - 你在哪找的？还是自己部署的？有相应仓库吗

**Comment by zkeq** [comment]
> pdf-for-onedrive.vercel.app - 你在哪找的？还是自己部署的？有相应仓库吗

有的,是自己部署的,之前玩oss的时候捣鼓的,正好用上了

而且我加了分片加载功能,原先的pdfjs是全部加载完成后再显示,返回码是200

我这个返回码是206,应该相对来说更快一点

方法是百度出来的....

仓库地址:

https://github.com/zkeq/pdf-js-learn

**Comment by zkeq** [comment]
> pdf-for-onedrive.vercel.app - 你在哪找的？还是自己部署的？有相应仓库吗

大文件测试视频链接:https://public-zkeq.oss-cn-beijing.aliyuncs.com/pdf-test.mp4

**Comment by spencerwooo** [comment]
> 仓库地址:
>
> [zkeq/pdf-js-learn](https://github.com/zkeq/pdf-js-learn)

私有的仓库诶 @zkeq

**Comment by zkeq** [comment]
> > 仓库地址:
> > [zkeq/pdf-js-learn](https://github.com/zkeq/pdf-js-learn)
> 
> 私有的仓库诶 @zkeq

啊,抱歉,请再次查看...

**Comment by myl7** [comment]
我也遇到了一样的状况，而 author 的网站下就没有这个问题。
而且不限于 mobile 和 firefox，我在 chrome desktop 下也能复现。
根据 Network Tab 的信息，以及一点之前的经验，我猜测应该是因为短时间内的复数次访问触发了 OneDrive API 的限制。
OneDrive API 的 download url 是有 CORS allow * 的，但是触发限制时的 error response 是没有 CORS 的，所以会直接被 CORS block 掉。
而 author 的网站下就只有一次访问，也就不会触发限制，也就没有 CORS error。
至于 pdf.js 为什么会多次 fetch 同一 url 就不清楚了……

**Comment by zkeq** [comment]
> 至于 pdf.js 为什么会多次 fetch 同一 url 就不清楚了……

用我提供的地址还会出现这个问题吗?

我看了下, 我那个 `pdf.js` [仓库](https://github.com/zkeq/pdf-js-learn) 应该一共做了3处改动且均在 `viewer.js` 上面..

https://github.com/zkeq/pdf-js-learn/blob/main/viewer.js

第一处:
`157` 行 : [链接](https://github.com/zkeq/pdf-js-learn/blob/593f1c449362134d7622a17afaab2587993b2b29/viewer.js#L157)
```
 disableAutoFetch: {
-    value: false,
+    value: true,
    kind: OptionKind.API + OptionKind.PREFERENCE
  },
```

第二处:
`2193-2195` 行 :  [链接](https://github.com/zkeq/pdf-js-learn/blob/593f1c449362134d7622a17afaab2587993b2b29/viewer.js#L2193-L2195)
```
-      if (origin !== viewerOrigin && protocol !== "blob:") {
-        throw new Error("file origin does not match viewer's");
-      }
+      // if (origin !== viewerOrigin && protocol !== "blob:") {
+        // throw new Error("file origin does not match viewer's");
+      // }
```

第三处:
`13719` 行 : [链接](https://github.com/zkeq/pdf-js-learn/blob/593f1c449362134d7622a17afaab2587993b2b29/viewer.js#L13719)
```
-        "disableAutoFetch": false,
+        "disableAutoFetch": true,
```





其他提交均为无效改动

**Comment by myl7** [comment]
![image](https://user-images.githubusercontent.com/49339031/151185934-f92ae819-4aee-48b3-8a61-561e0e62a758.png)

会，只是不会因为这些 request 失败而报错

**Comment by zkeq** [comment]
> 会，只是不会因为这些 request 失败而报错

那就奇怪了 我建的网站是教育版的好像, 换成我这个之后就没有报错了...

网站地址: https://tuostudy.vercel.app

**Comment by myl7** [comment]
![image](https://user-images.githubusercontent.com/49339031/151187232-37335ae5-17d1-4845-925c-cf6400234aea.png)

确实不会报错，但是 pdf.js 依然是 fetch 了 3 次并且其中 2 次失败了，第 1 次成功了。
1 次成功就应当足够进行 PDF 渲染了，但未修改过的 pdf.js 会因为后两次莫名其妙的 fetch 且失败而报错……

**Comment by zkeq** [comment]
> 确实不会报错，但是 pdf.js 依然是 fetch 了 3 次并且其中 2 次失败了，第 1 次成功了。

看起来很诡异 但是我的 `Edge` 或者 `Chrome` 3 次 fetch 均成功, 换成 `Firefox` 则有 2 次失败

手机端 测试用的浏览器是 `Kiwi Browser` ,也是 2 次报错

![Edge](https://edu-image.nosdn.127.net/7F2E27164A17F3EAC2E710FE14D799AB.png)

![Chrome](https://edu-image.nosdn.127.net/F12A85EA0AF76325A4F6F1309C30A57A.png)

![Firefox](https://edu-image.nosdn.127.net/829933B011CC36214B006A61968B2D18.png)

![phone](https://edu-image.nosdn.127.net/CB9876C47340E6CF875556841D675C6F.jpg)

**Comment by myl7** [comment]
后两个失败的 request 有 `Range` header，应该是 pdf.js 想多线程，但是撞上 OneDrive API 的 rate limit 了。

**Comment by myl7** [comment]
应该不是 rate limit 的问题，cURL 发 OPTIONS 也会 405

**Comment by myl7** [comment]
response `Allow` header 里明明有 `OPTIONS`，但 curl -X OPTIONS 直接 405……搞不明白了

**Comment by myl7** [comment]
author 的 download url 就接受 OPTIONS，我的 E5 developer subscription 就不接受 OPTIONS，这应该就是主要原因了

**Comment by zkeq** [comment]
> 后两个失败的 request 有 `Range` header，应该是 pdf.js 想多线程

我上面截图可以看到 第一次的返回码是 `200`  后两次的返回码是 `206`

或许是因为 206 的原因 ?

**Comment by myl7** [comment]
应该是的，206 Partial Content 是正常的回应，405 Method Not Allowed 就令人迷惑了

**Comment by spencerwooo** [comment]
所以说？到底是怎么个问题呢？我是修还是不修呢

**Comment by myl7** [comment]
应该不是 pdf.js demo viewer 的问题，应该是 OneDrive API 的问题，而且也不清楚触发的具体条件是什么，只有一些 OneDrive API unexpected responses。

**Comment by wc7086** [comment]
> 而且我加了分片加载功能,原先的 pdf.js 是全部加载完成后再显示

这导致 safari 加载比较大或者页数比较多的PDF的时候直接崩了，webkit内核真的辣鸡。: (

**Comment by SuInk** [comment]
请问你在播放mp4格式视频的时候会出问题吗？

**Comment by SuInk** [comment]
> > 请问你在播放mp4格式视频的时候会出问题吗？
> 
> 什么问题？

没事了，好像是ios录制视频格式的问题，我在电脑上转码了一下就没问题了

**Comment by Huiaei** [comment]
挺离谱的，没想到Firefox不支持自家。看文档firefox全部报错，之后就是提示下载。
```
PDF.js v2.14.73 (build: 489e9ff7d)
信息：NetworkError when attempting to fetch resource.
```
看完整个issues，换了edge浏览器没想到是能正常打开预览的。

**Comment by n0099** [comment]
> 应该不是 pdf.js demo viewer 的问题，应该是 OneDrive API 的问题，而且也不清楚触发的具体条件是什么，只有一些 OneDrive API unexpected responses。

我去年跟国内代理商世纪互联客服扯过皮，他们认为：
> OPTIONS并不是我们常见的一个获取数据的方法，此方法可能就是不被支持的。
> 常用的方式是通过Graph API来获取数据，可以从官方文档中看到，也是只支持GET方法，没有OPTIONS方法

完整来往邮件：[Re_SR_2021041390874_SharePoint服务端不支持method为OPTIONS的浏览器CORS+preflight请求.zip](https://github.com/spencerwooo/onedrive-vercel-index/files/8843362/Re_SR_2021041390874_SharePoint.method.OPTIONS.CORS%2Bpreflight.zip)

**Comment by spencerwooo** [comment]
Closing this for now. Reopen a new issue if this is still worth discussing.
