### ISSUE TITLE
[Request] Ability to set the 'userPrincipalName' obfuscated

### ISSUE THREAD

**Issue by l3v11** [spencerwooo/onedrive-vercel-index#301]
It will be nice to have this, since we are doing fork and adding our configs on public repo. Don't wanna make the email public 🙂 for security purposes. Hope you take this under consideration.

**Comment by spencerwooo** [comment]
I'm thinking of converting config files into `.config.js`, so that we can also use environment variables in them directly.

Putting your `userPrincipalName` in environment variables would definitely hide your email in production environments.

Thoughts?

**Comment by l3v11** [comment]
Yeah it seems nice
