### ISSUE TITLE
Ability to show full names on mobile browser

### ISSUE THREAD

**Issue by l3v11** [spencerwooo/onedrive-vercel-index#305]
Currently mobile view doesn't show the full file name.. It also does the same on big screen to if file name is big
Ex.
I am a boy (202..........
She is a girl (20.........
They are men (..........

It would be nice if you add support for showing full file names along with file size. Hope you take this under consideration.

**Comment by myl7** [comment]
Adding a `title` attribute for the filename text should be enough for desktop.
But mobile devices can not easily hover. Another method is required.

**Comment by spencerwooo** [comment]
One can only do so much for mobile layouts - hiding most of the elements to show the most important ones.

If - and *really* it means if I feel like it some time later this year - we eventually have some sort of 'grid view', only by then will we consider showing more file content on mobile.

(I'm going to mark this as `wontfix` for now, but will leave this open.)

**Comment by BrandonStudio** [comment]
@spencerwooo Onedrive displays the first and last several characters, which looks like
> com.king.can...1.219.0.6.apk

instead of only the first ones like
> com.king.candycrushsaga_1...

Do you consider using former case?

**Comment by BrandonStudio** [comment]
Or perhaps you can use a horizental scroll bar to show full name and other attributes just like hashes boxes in file info pages?

**Comment by spencerwooo** [comment]
Closing in favor of #406
