### ISSUE TITLE
缩略图显示有问题

### ISSUE THREAD

**Issue by MCSeekeri** [spencerwooo/onedrive-vercel-index#316]
![image](https://user-images.githubusercontent.com/20928094/151187691-f716b086-1aea-4653-9d95-0697d741e4a3.png)
底部缩略图无法正常显示。
其实选用fancybox作为图片预览也不错...?

**Comment by spencerwooo** [comment]
也不叫无法正常显示吧，这个库就是这么个效果。其实有在考虑做 list view 和 grid view 切换的，实际上也就不用这种预览了。未来可期一下？

**Comment by People-11** [comment]
> 也不叫无法正常显示吧，这个库就是这么个效果。其实有在考虑做 list view 和 grid view 切换的，实际上也就不用这种预览了。未来可期一下？

P.S. 似乎在图片较多的文件夹中进行预览会消耗大量CPU资源并引起界面严重卡顿（下方缩略图加载时），这是否可以优化？

**Comment by spencerwooo** [comment]
Closing in favor of PR #350
