### ISSUE TITLE
Tab switching triggers PDF preview reloading

### ISSUE THREAD

**Issue by myl7** [spencerwooo/onedrive-vercel-index#317]
https://user-images.githubusercontent.com/49339031/151225264-5864a4bb-bf9f-4eda-bdfb-c5a29a13a6c9.mp4

In PDF preview page, when switching tabs or close debug console, pdf.js in iframe will unexpectedly redownload and rerender the original PDF.

**Comment by zkeq** [comment]
Not only is the PDF, `video` and `audio` will appear this kind of circumstance.

 As long as the browser loses focus, switch back again will appear this kind of situation

Video Test: [Link](https://tuostudy.vercel.app/%E2%AD%90%202%23%20%E5%8D%95%E8%AF%8D%E8%A7%86%E9%A2%91/%F0%9F%93%81%20%E4%B8%8D%E8%83%8C%E5%8D%95%E8%AF%8D/%F0%9F%93%81%203%23%20%E9%AB%98%E8%80%83/%E4%B8%80%E5%B0%8F%E6%97%B6%E5%88%B7%E5%AE%8C%E9%AB%98%E8%80%83%E7%9C%9F%E9%A2%98%E9%AB%98%E9%A2%91%E8%AF%8D%20(%E5%8F%8C%E8%AF%AD).mp4) 

Audio Test: [Link](https://tuostudy.vercel.app/%F0%9F%92%8E%2093%23%20%E5%88%9B%E4%BD%9C%E7%81%B5%E6%84%9F/%F0%9F%93%81%20%E9%92%A2%E7%90%B4%E7%BA%AF%E9%9F%B3%E4%B9%90BGM/%E2%9C%94Phildel%20-%20Dragonfly%20Keeper.mp3)  

https://user-images.githubusercontent.com/62864752/151272064-203bc048-0538-4078-96a1-e0574ae665ff.mp4

**Comment by spencerwooo** [comment]
Right, I believe this is still an issue caused by `useSWR`, where it revalidates data on refocus, causing a reload.

**Comment by spencerwooo** [comment]
File listing is fetched with a custom `useProtectedSWRInfinite` (for fetching password protected routes and adding pagination support). The revalidate option is defined there also.

You can temporarily uncomment https://github.com/spencerwooo/onedrive-vercel-index/blob/main/utils/fetchWithSWR.ts#L63-L68 and see if that mitigates the issue.

The options were there before I implemented the custom `useAxiosGet` hook, as the revalidate was causing README.md rerenders between page navigations. I thought `useAxiosGet` solved the revalidation issue so I commented out the options.

**Comment by zkeq** [comment]
> You can temporarily uncomment https://github.com/spencerwooo/onedrive-vercel-index/blob/main/utils/fetchWithSWR.ts#L63-L68 and see if that mitigates the issue.

I  uncommented   this code , I think it worked for me .  👍

[Video Test Link](https://onedrive.zkeq.xyz/%E2%AD%90%202%23%20%E5%8D%95%E8%AF%8D%E8%A7%86%E9%A2%91/%F0%9F%93%81%20%E4%B8%8D%E8%83%8C%E5%8D%95%E8%AF%8D/%F0%9F%93%81%20%E3%80%90%E5%8D%95%E8%AF%8D%E6%89%8B%E5%86%99%E6%9C%AC%E3%80%91%EF%BC%88%E9%85%8D%E5%90%88%E5%B9%B3%E6%9D%BF%E6%89%8B%E5%86%99%E7%AC%94%E4%BD%BF%E7%94%A8%EF%BC%89/2022%E8%80%83%E7%A0%94%E7%BA%A2%E5%AE%9D%E4%B9%A6%E7%BE%8E%E9%9F%B3%20(1).mp4)

[Audio Test Link](https://onedrive.zkeq.xyz/%F0%9F%92%8E%2093%23%20%E5%88%9B%E4%BD%9C%E7%81%B5%E6%84%9F/%F0%9F%93%81%20%E5%AD%A6%E4%B9%A0%E5%B7%A5%E4%BD%9C%E5%BF%85%E5%A4%87%E6%AD%8C%E5%8D%95/A%20Veil%20Of%20Water%20-%20Fall.mp3)

[Pdf Test Link](https://onedrive.zkeq.xyz/%F0%9F%8C%9E%205%23%20%E5%AD%A6%E4%B9%A0%E8%B5%84%E6%96%99/%F0%9F%93%81%20%E6%97%A5%E8%AF%AD/%E6%96%B0%E7%89%88%E4%B8%AD%E6%97%A5%E4%BA%A4%E6%8D%A2%E6%A0%87%E5%87%86%E6%97%A5%E6%9C%AC%E8%AF%AD%E5%88%9D%E7%BA%A7%E4%B8%8A%E5%86%8C%E8%AF%BE%E6%96%87%E8%AF%91%E6%96%87%E5%8D%95%E8%AF%8D.pdf)
