### ISSUE TITLE
PDF Viewer Not Working On Phone

### ISSUE THREAD

**Issue by People-11** [spencerwooo/onedrive-vercel-index#326]
![Screenshot_20220130-065554_Chrome](https://user-images.githubusercontent.com/41558215/151680224-d4a39405-c7f0-44e5-a1de-b2132a8bb9c4.png)

**Comment by zkeq** [comment]
It seems that you have the same problem as this #300 

Please try the solutions provided. 

https://github.com/spencerwooo/onedrive-vercel-index/issues/300#issuecomment-1022268141

Replace `https://mozilla.github.io/pdf.js/web/viewer.html?file=` to `https://pdf-for-onedrive.vercel.app/?file= .`  

Maybe this will work?

**Comment by People-11** [comment]
> 

This work, thanks. :)
