### ISSUE TITLE
About  REDIS_URL  in  doc

### ISSUE THREAD

**Issue by wxydejoy** [spencerwooo/onedrive-vercel-index#331]
It's easy to make mistakes when getting REDIS_URL, because most people are not familiar with the format of the link. Therefore, I suggest attaching the format of the link to the document and emphasizing it or properly guiding users to get the correct link, like this.

**`redis://:xxxxxxxxxxxxx@global-classic-sheep-31244.upstash.io:31244`**
![image](https://user-images.githubusercontent.com/81625961/151700502-74c0e849-01c7-4a03-a801-22c052bfc4ad.png)

**Comment by spencerwooo** [comment]
Noted, will reflect this in the new docs.

**Comment by spencerwooo** [comment]
https://onedrive-vercel-index.spencerwoo.com/docs/getting-started#create-a-redis-connection
