### ISSUE TITLE
Weird Music Player Interface On Phone

### ISSUE THREAD

**Issue by People-11** [spencerwooo/onedrive-vercel-index#348]
![Screenshot_20220203-215410_Chrome~2](https://user-images.githubusercontent.com/41558215/152356701-70369b19-5b6b-4762-a19c-a42d2652099d.png)
I recommend using Default Preview (show file details) to replace the spinning music icon in the music interface.

**Comment by spencerwooo** [comment]
![image](https://user-images.githubusercontent.com/32114380/152358727-847d5fb8-8b6e-4131-88d5-b5e3212e6c16.png)

What device are you using? Looks fine on iPhone.

**Comment by spencerwooo** [comment]
Also it seems like you have changed some of the code, I'm not responsible for bugs occuring on your forks.

**Comment by spencerwooo** [comment]
The square attribute is defined by `aspect-square` in tailwind: https://tailwindcss.com/docs/aspect-ratio#browser-support

It is styled with the CSS property `aspect-ratio`: https://caniuse.com/mdn-css_properties_aspect-ratio

<img width="1553" alt="CleanShot 2022-02-03 at 22 24 40@2x" src="https://user-images.githubusercontent.com/32114380/152361468-efa9d2d8-6001-48a5-9e67-a29cafd39c86.png">

Seems like Android browsers are all supported.

**Comment by People-11** [comment]
Oh, I am using Chrome 83, so that's my problem :)
