### ISSUE TITLE
當前的API是否支持一次性獲得200個或以上數量的文件列表？

### ISSUE THREAD

**Issue by kobe-koto** [spencerwooo/onedrive-vercel-index#365]
一次性似乎只能夠取得200個

**Comment by spencerwooo** [comment]
200 个是上游 Microsoft Graph API 的限制喔，再多了不行的

**Comment by kobe-koto** [comment]
> 200 个是上游 Microsoft Graph API 的限制喔，再多了不行的

好的
在項目裏同文件夾下超過200個檔案時是分頁進行讀取的，那麽是否可以分次獲取？🤔

**Comment by 0wQ** [comment]
https://docs.microsoft.com/zh-cn/graph/query-parameters#top-parameter
可以使用 top 参数修改
我测试512个文件可以，再多就没再测了
![image](https://user-images.githubusercontent.com/20741439/152762323-b11cd77d-7b56-4937-8491-095b7fde3593.png)

**Comment by kobe-koto** [comment]
> https://docs.microsoft.com/zh-cn/graph/query-parameters#top-parameter 可以使用 top 参数修改 我测试512个文件可以，再多就没再测了 ![image](https://user-images.githubusercontent.com/20741439/152762323-b11cd77d-7b56-4937-8491-095b7fde3593.png)

好的謝謝

**Comment by spencerwooo** [comment]
你说的「分頁進行讀取」和「分次獲取」的区别是什么？不都是 pagination 吗？
