### ISSUE TITLE
OneDrive for Business 加载缓慢

### ISSUE THREAD

**Issue by hmsjy2017** [spencerwooo/onedrive-vercel-index#40]
使用 OneDrive for Business，即使目录中只放了一个文件，加载时间也长达 2.53 s。而OneDrive个人版，一个有20多个文件的目录，加载时间才773 ms。而且每次商业版都比个人版加载速度慢很多。似乎是 API 的问题。
## OneDrive 个人版
加载时间：735 ms
![image](https://user-images.githubusercontent.com/42692274/128301052-8607524e-8108-4b11-a5d8-9a030fefc4f5.png)
## OneDrive for Business 
加载时间：4.53 s
![image](https://user-images.githubusercontent.com/42692274/128301074-781b9b72-2471-4d2f-bc6d-3106206613ee.png)

**Comment by spencerwooo** [comment]
我没有可供测试的 OneDrive for Business 账号，但是就算有项目这边能做什么来解决这个问题吗？
