### ISSUE TITLE
功能建议：搜索文件、预览 EPUB

### ISSUE THREAD

**Issue by hmsjy2017** [spencerwooo/onedrive-vercel-index#41]
搜索功能应该可以通过 OneDrive 的 API 来实现
官方文档：https://docs.microsoft.com/zh-cn/onedrive/developer/rest-api/api/driveitem_search?view=odsp-graph-online#searching-for-items-a-user-can-access
EPUB 预览功能可以用这两个开源库来实现
https://github.com/futurepress/epub.js
https://github.com/gerhardsletten/react-reader

**Comment by aozaki-kuro** [comment]
OneDrive的官方搜索API…
它几乎只能搜索英文和数字，而且准确性有时要打一个挺大的问号;
而一旦涉及到CJK那几乎是废的。

之前看过OLAINDEX用户自己弄了一个Google Search的搜索框，不知道是如何实现外部搜索引擎搜索的。

**Comment by hmsjy2017** [comment]
@aozaki-kuro 可以在谷歌搜索框里输入`site:域名 关键词`进行搜索，但要谷歌收录才行（我用的OneManager谷歌有收录，但不全）。嵌入搜索框其实也不难实现。比如我的域名是`pan.iamsjy.com`，搜索框搜索关键词跳转到`https://www.google.com/search?q=site%3Apan.iamsjy.com%20${关键词}`就行了。

**Comment by spencerwooo** [comment]
搜索估计暂时不会考虑了，不过 `.epub` 的预览倒是支持上了（via #133）。
