### ISSUE TITLE
功能建议：支持.avi格式预览及字幕功能

### ISSUE THREAD

**Issue by 1286058233** [spencerwooo/onedrive-vercel-index#43]
增加个导出到其它播放器的接口也OK♥

**Comment by spencerwooo** [comment]
`avi` 格式的视频预览不支持，详见：https://stackoverflow.com/questions/4129674/does-html5-video-playback-support-the-avi-format

**Comment by spencerwooo** [comment]
![Screenshot 2021-08-15 at 21 26 33](https://user-images.githubusercontent.com/32114380/129491746-c401d7fb-c830-4548-a465-4c61142af984.png)
