### ISSUE TITLE
Last Modified样式修改

### ISSUE THREAD

**Issue by aozaki-kuro** [spencerwooo/onedrive-vercel-index#45]
![image](https://user-images.githubusercontent.com/28428951/129432633-87bb0a04-2798-4440-805e-a3c8e9480e2c.png)
现在这样长长短短说实话挺难看的

提议修改为
```
yyyy/MM/dd HH:mm
```
样式以使整栏对齐。

**Comment by spencerwooo** [comment]
![Screenshot 2021-08-14 at 15 09 43](https://user-images.githubusercontent.com/32114380/129449003-0dbc84e8-5076-44d2-93d9-6a9ce72c0ba5.png)

大意了，`toLocaleString` 默认简中才会有这个问题，后面把语言写死 `en-US` 吧。

**Comment by Mahoo12138** [comment]
我也注意到这个了，然后我写了几行的格式转换🤣

**Comment by aozaki-kuro** [comment]
> ![Screenshot 2021-08-14 at 15 09 43](https://user-images.githubusercontent.com/32114380/129449003-0dbc84e8-5076-44d2-93d9-6a9ce72c0ba5.png)
> 
> 大意了，`toLocaleString` 默认简中才会有这个问题，后面把语言写死 `en-US` 吧。

话说dd/MM/yyyy看起来还是挺难受的…是否可以考虑转换成`yyyy/MM/dd HH:mm`？

**Comment by spencerwooo** [comment]
> 话说 dd/MM/yyyy 看起来还是挺难受的…是否可以考虑转换成 yyyy/MM/dd HH:mm？

我说了，现在这个是默认语言（locale）决定的，我在英国所以这个日期格式是 `en-GB`
