### ISSUE TITLE
File direct download icon

### ISSUE THREAD

**Issue by spencerwooo** [spencerwooo/onedrive-vercel-index#50]
Download files directly via download button in the listing view.

### Discussed in https://github.com/spencerwooo/onedrive-vercel-index/discussions/49

<div type='discussions-op-text'>

<sup>Originally posted by **cgmark101** August 15, 2021</sup>
Hi man, thanks for this awesome tool. Is there a way to direct download a video without redirecting to the embeded player?</div>

**Comment by EmilRdz** [comment]
Yes, but the button show direct url onedrive for download multimedia. I like can download multimedia with links of indexator, not from onedrive.
