### ISSUE TITLE
cache-control is set to private for some reason.

### ISSUE THREAD

**Issue by kotx** [spencerwooo/onedrive-vercel-index#522]
For the endpoint(s) /api/raw/?path=/a.png
![image](https://user-images.githubusercontent.com/33439542/156904936-5eceef93-a1f0-43b8-8c79-3547a8766bfd.png)
This should be set to `public` for public files/folders and `private` for private/locked ones. However, I don't see why it would ever be set to `private` in the source code. Maybe something is overwriting the headers or I'm missing something here?

**Comment by spencerwooo** [comment]
https://github.com/spencerwooo/onedrive-vercel-index/blob/7eb786025382146b6dbea478929c8e491e917594/pages/api/raw.ts#L57

The `/api/raw` route's cache is only modified here, and I don't think I ever tinkered with the `private` or `public` settings of `Cache-Control` throughout the project either?

**Comment by spencerwooo** [comment]
anyway, closing this for now. reopen if you think it's something with what i wrote in the code. ;)
