### ISSUE TITLE
搜索特定词会导致错误

### ISSUE THREAD

**Issue by V-Conet** [spencerwooo/onedrive-vercel-index#539]
当搜索`a` `p` `_` `l`等会稳定触发bug
```
Application error: a client-side exception has occurred (see the browser console for more information).
```

控制台输出
![](https://s3.bmp.ovh/imgs/2022/03/b8cdc6f74a085522.png)
  
输入`a`之类的有结果但迅速报错
未绑定域名,e5

地址: https://onedrive-v-conet.vercel.app

**Comment by V-Conet** [comment]
与 #353 情况相似，且353中的0001也会出错

**Comment by naicfeng** [comment]
[  const absolutePath = path.split(siteConfig.baseDirectory === '/' ? 'root:' : siteConfig.baseDirectory)[1]](https://github.com/spencerwooo/onedrive-vercel-index/blob/0397fcd52f770d56687e7092302e11f8e9ffe229/components/SearchModal.tsx#L30)

超出了数组下标，增加判断即可修复

**Comment by V-Conet** [comment]
> https://github.com/spencerwooo/onedrive-vercel-index/blob/0397fcd52f770d56687e7092302e11f8e9ffe229/components/SearchModal.tsx#L30
> 
> 超出了数组下标，增加判断即可修复

已解决
