### ISSUE TITLE
404 txt files

### ISSUE THREAD

**Issue by 1208nn** [spencerwooo/onedrive-vercel-index#540]
404error previewing md,log,txt files

t.data.text is not a function. (In 't.data.text()', 't.data.text' is undefined)

**Comment by spencerwooo** [comment]
could you please attach a file that causes such an error? thanks.

**Comment by spencerwooo** [comment]
我没看懂，演示站中文下 README 在手机端显示 404？是这个意思吗？但我无法复现。

<img src="https://user-images.githubusercontent.com/32114380/158509330-a3d53759-d712-4f61-aa21-f18bd5f7aa79.png" width="400px" />

**Comment by 1208nn** [comment]
![18DB1C26-19D3-4892-AD56-3EE6183AA7EF](https://user-images.githubusercontent.com/74806550/158616940-2d337478-9020-46cd-80f9-96e005af25fa.png)

**Comment by 1208nn** [comment]
多次测试
只有ipad无法使用,出现404

**Comment by spencerwooo** [comment]
我怀疑是网络问题？暂时 close 了。

**Comment by 1208nn** [comment]
由cloudflare dns 的域名 md等文件预览显示network error, vercel.app 上的可以正常使用

部分文件的中文部分乱码，显示为‘�’
