### ISSUE TITLE
Using completely numeral password causes a `500 Internal Error` with password-protected routes

### ISSUE THREAD

**Issue by code004Accepted** [spencerwooo/onedrive-vercel-index#606]
核实：下述问题仅在密码为纯数字时出现。

一旦将密码改为非纯数字，即可正常使用。

---

### Discussed in https://github.com/spencerwooo/onedrive-vercel-index/discussions/605

<div type='discussions-op-text'>

<sup>Originally posted by **code004Accepted** April 17, 2022</sup>
Possible duplicate with #570 

---

Site: https://drive.ender.ml/%F0%9F%8F%ABSchool/%F0%9F%93%9C2022%20NEMT%20Preparation%20Materials/
Configuration Files: https://github.com/code004Accepted/onedrive-vercel-index/blob/main/config/site.config.js#L42
Screenshot: 

<img width="477" alt="Screenshot 2022-04-17 142426" src="https://user-images.githubusercontent.com/36566134/163703336-e441dedf-fa4b-4e2e-b0f6-46907edb57a5.png">

---

Additional Info: There were other password protected routes on my site but they all worked well. Only this route triggered an error.

<img width="624" alt="Screenshot 2022-04-17 142819" src="https://user-images.githubusercontent.com/36566134/163703412-b2cd5923-f154-422e-b32f-ec5b3da5a02f.png">

The `.password` file contained no longer than an 8-digit number and it should be error-free.

<img width="245" alt="Screenshot 2022-04-17 143053" src="https://user-images.githubusercontent.com/36566134/163703469-3cf3c3b6-ec66-49e3-918a-451a9a075422.png"></div>

**Comment by CryZJ** [comment]
我也遇到了同样的问题，不过没有发现是纯数字原因导致，感谢你提供了一种变通的解决方法。XD

**Comment by spencerwooo** [comment]
了解，后续修复 :)
