### ISSUE TITLE
图片直连出现 500：Internal Server Error.

### ISSUE THREAD

**Issue by Huiaei** [spencerwooo/onedrive-vercel-index#61]
图片在网页内可预览，复制直连到地址栏出现500：Internal Server Error.
视频文件未发现此问题。

应该与文件夹层级无关，同层数的视频可以激活下载，并且链接长度也大于图片。

**Comment by spencerwooo** [comment]
大意了，上次修带 `#` 的路径的时候，全局替换把复制到剪贴板的路径也 `encodeUrlComponent` 了。现在应该修好了。
