### ISSUE TITLE
Fullscreen video player on iOS Safari

### ISSUE THREAD

**Issue by spencerwooo** [spencerwooo/onedrive-vercel-index#611]
### Discussed in https://github.com/spencerwooo/onedrive-vercel-index/discussions/579

<div type='discussions-op-text'>

<sup>Originally posted by **wejudging** April  1, 2022</sup>
iOS 端 Safari 浏览器看视频无法全屏
</div>

**Comment by myl7** [comment]
After merging #678 :

> However, subtitles will not be visible in full screen this way, even if the Show subtitles option is available and turned on in the system player.
