### ISSUE TITLE
iOS设备播放flv视频的时候加载flv插件失败

### ISSUE THREAD

**Issue by gitLinan** [spencerwooo/onedrive-vercel-index#619]
错误信息如下：
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred

![image](https://user-images.githubusercontent.com/33097694/164964522-46847271-ba26-4a24-981f-8aa9cb50330f.png)

X 测试了iOS系统三款浏览器都是一样的错误 Safari，Chrome，Alook

✓ 测试了macos系统的Safari chrome都可以正常播放 

测试视频可以用以下链接
https://od.mobai.ml/zh-CN/%E5%85%B1%E4%BA%AB/%E8%AF%BE%E4%BB%B6/%E9%BB%91%E9%A9%AC-javaEE57%E6%9C%9F/01%20%E8%AF%AD%E8%A8%80%E5%9F%BA%E7%A1%80%2B%E9%AB%98%E7%BA%A7/1-1-Java%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95/%E7%AC%AC12%E8%8A%82%20%E6%96%B9%E6%B3%95%E5%A4%8D%E4%B9%A0/1_1_12_08_%E5%A4%8D%E4%B9%A0%E7%AE%80%E5%8D%95%E6%96%B9%E6%B3%95%E7%9A%84%E4%BD%BF%E7%94%A8.flv

**Comment by gitLinan** [comment]
补充一下

机型 ： iPhone xs max 国行
系统版本 ： iOS15.4.1

**Comment by myl7** [comment]
iOS 中的 Safari 浏览器上没有 MSE 支持，所以无法在浏览器里播放 FLV 视频且没有可行的解决方案。

**Comment by gitLinan** [comment]
> iOS 中的 Safari 浏览器上没有 MSE 支持，无法在浏览器里播放 FLV 视频并且没有什么解决方案。

好的 收到，这个做一项提示吧 以防之后还有人纠结
