### ISSUE TITLE
可以设置关闭预览功能吗？

### ISSUE THREAD

**Issue by maplefz** [spencerwooo/onedrive-vercel-index#62]
能设置关闭预览功能吗？

**Comment by spencerwooo** [comment]
最最最…最原版的没有预览功能：[heymind/OneDrive-Index-Cloudflare-Worker](https://github.com/heymind/OneDrive-Index-Cloudflare-Worker)

（我辛辛苦苦实现的各种文件预览你竟然觉得没用 😭）

**Comment by maplefz** [comment]
这个真不好意思了，是我的需求比较奇葩。用cf怕超额度，我自己修改一下仓库里的文件了。。也感谢开发这个好看又好用的程式。
