### ISSUE TITLE
视频预览页异常

### ISSUE THREAD

**Issue by DogTorrent** [spencerwooo/onedrive-vercel-index#626]
问题比较诡异，我有一个视频以前是可以播放的，但是现在播不出来了，甚至视频都还没307到原链接页面就炸了
我试着改了代码，让所有视频的videoUrl都写死为这个视频的地址(/api/raw那个)，然后这个视频自己的预览页还是会炸，但是进到其他视频的预览页却可以正常播放这个视频（说明应该不是文件内容的问题）

我部署的代码改了不少，但是这个问题是在我改动代码前就有的，大概是在试完 #589 后就不行了，本来怀疑是不是文件被微软ban了，但是试了下raw链接又还可以用

炸了会报`Application error: a client-side exception has occurred (see the browser console for more information).`，画面是这样：
![图片](https://user-images.githubusercontent.com/39661453/165932581-4ff2fdfb-7aac-48ea-9061-2a1c1e840d12.png)

[测试文件](https://onedrive.hitachimako.top/Public/test.mkv)，因为是mkv+hevc所以得用edge开，od对mkv返回的mime类型是application/octet-stream，firefox不支持播放（即使支持也放不出hevc来）

**Comment by wc7086** [comment]
firefox并不支持hevc

https://caniuse.com/?search=hevc

**Comment by DogTorrent** [comment]
> firefox并不支持hevc
> 
> https://caniuse.com/?search=hevc

这个我知道，但是这个问题应该和hevc没啥关系，我用的edge，我存的其他hevc都是能看的。而且它是在视频文件从api/raw redir到原地址之前就崩溃了的

**Comment by wc7086** [comment]
哦，看了一下，firefox自身不支持软解而已，但早就能调用系统自带的解码器了，看来不是firefox的问题。

**Comment by DogTorrent** [comment]
> 哦，看了一下，firefox自身不支持软解而已，但早就能调用系统自带的解码器了，看来不是firefox的问题。

其实firefox调硬解也不支持hevc，chromium倒是可以自己改参数编译增加支持
但咱是不是偏题了（）

**Comment by wc7086** [comment]
我试了一下我存的视频，以前能正常看的 *Mr.Robot* 现在 firefox 上一直加载不跑流量，啥编码的我忘了，容器是 MKV。还有 MP4 的 *Yes Minister* 和 *Yes Prime Minister* 在 firefox 是能播放，但没声音，其他一些从视频平台下载的 MP4 视频倒是能正常播放声音。

*Mr.Robot* 在 chromium 上能播放，但还是没声音。

**Comment by DogTorrent** [comment]
> 我试了一下我存的视频，以前能正常看的 *Mr.Robot* 现在 firefox 上一直加载不跑流量，啥编码的我忘了，容器是 MKV。还有 MP4 的 *Yes Minister* 和 *Yes Prime Minister* 在 firefox 是能播放，但没声音，其他一些从视频平台下载的 MP4 视频倒是能正常播放声音。
> 
> *Mr.Robot* 在 chromium 上能播放，但还是没声音。

既然能播，那应该就是浏览器解码的问题，和这个项目/这个issue都没啥关系。另外关于firefox播放不了mkv的锅应该让微软/ff来背（微软给了mkv一个有问题的mime，ff不支持），更和这个项目/issue没啥关系了

**Comment by spencerwooo** [comment]
Closing this for now as it seems unrelated to the project iteself.
