### ISSUE TITLE
搜索功能可以搜到账户下所有的文件，即使没有在设定的网盘路径中

### ISSUE THREAD

**Issue by qilme** [spencerwooo/onedrive-vercel-index#649]
如题，虽然点击访问这些文件是不行的，但是文件名多少会泄露点隐私。

比如输入`.`搜索，由于几乎所有文件都有后缀，所以相当于可以看到所有文件。

我的方法是使用一个新号，更换账号可能要删除token，我不知道token保存在哪，所以全部删除重来了一遍，最后成功了。

现在看来不需要这么麻烦，更改了config之后，在这个路径下`/zh-CN/onedrive-vercel-index-oauth/step-1/`重新认证一遍就行了

**Comment by myl7** [comment]
这是期望中的行为，具体情况可以参见 #618

不过我也在策划一套手动剔除搜索结果的方案，**依然会泄露文件名**，但能够至少在视觉上减少受保护文件的展示，具体实现可以参见 https://github.com/myl7/onedrive-vercel-index/tree/search-auth

**Comment by qilme** [comment]
谢谢你，我明白了。我要求的这种查询需要服务器支持，这难以做到完美。
