### ISSUE TITLE
How to maintain a dark mode?

### ISSUE THREAD

**Issue by coldpub** [spencerwooo/onedrive-vercel-index#655]
In some cases, the white mode is not applicable, how will I set up permanent dark mode?

**Comment by myl7** [comment]
Dark mode of the project is based on Tailwind CSS, which has [a guide](https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually) to show how to manually enable dark mode.

TL;DR: Set `darkMode: 'class'` in `tailwind.config.js`, and add `dark` class to the `<html>` element.

**Comment by coldpub** [comment]
Ok, I try it, thank you very much
