### ISSUE TITLE
部署在自己服务器时，似乎用户在访问时有概率触发报错导致运行中断...

### ISSUE THREAD

**Issue by zkeq** [spencerwooo/onedrive-vercel-index#656]
![1](https://user-images.githubusercontent.com/41193900/167084207-6a387cca-a665-483e-a73f-11d9e444dcbe.jpeg)

似乎是在相应的位置没有找到对应的文件，导致的报错
查看对应的文件夹，发现是空文件夹...
根据报错信息手动创建一个文件..可以暂时解决该问题
但是过一段时间之后又会触发...

(似乎每个人遇到的报错提示缺少文件也不一样...)

见其他人遇到的报错：

```bash
Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
Fetch access token from storage.
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/root/onedrive-vercel-index-main/.next/cache/images/6M+Uug4RD5HaF34NhM+YTomenh7aVRoZZMj+oflXH4E=/0.1653210833470.zfJIqygIR1do0k+ux8lv5PwMmbKdznimuo1NKKtx1sM=.webp'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/root/onedrive-vercel-index-main/.next/cache/images/6M+Uug4RD5HaF34NhM+YTomenh7aVRoZZMj+oflXH4E=/0.1653210833470.zfJIqygIR1do0k+ux8lv5PwMmbKdznimuo1NKKtx1sM=.webp'
}
 ELIFECYCLE  Command failed with exit code 1.
[root@VM-24-12-centos onedrive-vercel-index-main]# 
```

_Originally posted by @tmzncty in https://github.com/spencerwooo/onedrive-vercel-index/discussions/518#discussioncomment-2798577_

**Comment by zkeq** [comment]
相同问题：
- https://github.com/spencerwooo/onedrive-vercel-index/discussions/518#discussioncomment-2719290
- https://github.com/spencerwooo/onedrive-vercel-index/discussions/518#discussioncomment-2798577
- https://github.com/spencerwooo/onedrive-vercel-index/discussions/633#discussioncomment-2698653
- https://github.com/spencerwooo/onedrive-vercel-index/discussions/112#discussioncomment-2799037

**Comment by DaBoSAMA** [comment]
![image](https://user-images.githubusercontent.com/83501409/170017855-7312a25b-ce92-432f-97c3-80c911416fb6.png)
这个是我的image文件夹

![image](https://user-images.githubusercontent.com/83501409/170017940-72adf97b-2307-45e9-b792-85b2a3e0f5ec.png)
每个文件夹内都存着一张网站图片的缓存，这张是我的网站icon

正常情况下，每一个文件夹里都会有且只有一张图片文件。

![image](https://user-images.githubusercontent.com/83501409/170019734-f53e762f-ce24-4e1d-a1ff-7da30d4ce24e.png)
但是某些时候，这个文件就因为未知原因直接消失了，而且通常消失发生在用户访问网站的时候。这个时候，如果渲染网站需要这张图片的话，就会直接崩溃并在后台出现类似的错误，用户通常会看到渲染了一半的网页。

```
node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/root/onedrive-vercel-index/.next/cache/images/mlLb-9i1xsIIiYnKzumggWWcecEPFi4d-0FFPYmInPg=/0.1653250102559.PgakaNV7Rr4B2dO1I8qtNSDDVTYDaeowkIrDzzXqxjE=.webp'
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/root/onedrive-vercel-index/.next/cache/images/mlLb-9i1xsIIiYnKzumggWWcecEPFi4d-0FFPYmInPg=/0.1653250102559.PgakaNV7Rr4B2dO1I8qtNSDDVTYDaeowkIrDzzXqxjE=.webp'
}
?ELIFECYCLE? Command failed with exit code 1.
```


而且看起来所有使用自己服务器运行的这个项目都有这个问题
而且我按照您的方法手动创建文件占位置的话，会在网页需要这个图片的时候将文件自动覆盖成图片缓存，所以本质上应该是没有作用的
如果崩溃之后直接重新启动的话，如果项目没有找到上个缺失的文件，就会重新创建一个新的文件夹或者文件

**Comment by Zipper-1** [comment]
这个问题我将netxjs升级到12.2.5后不再复现，但是网站的样式设计会出现问题，部分图标和按钮会丢失样式信息

**Comment by spencerwooo** [comment]
> 但是网站的样式设计会出现问题，部分图标和按钮会丢失样式信息

Should be fixed.

**Comment by tmzncty** [comment]
对的，看起来需要docker了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月23日(周一) 中午1:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [spencerwooo/onedrive-vercel-index] 部署在自己服务器时，似乎用户在访问时有概率触发报错导致运行中断... (Issue #656)




 
相同问题：
  
#518 (reply in thread) 

#518 (reply in thread) 

#633 (reply in thread) 

#112 (comment)
