### ISSUE TITLE
EPUBPreview 获取文件参数错误？

### ISSUE THREAD

**Issue by NekoMio** [spencerwooo/onedrive-vercel-index#659]
https://github.com/spencerwooo/onedrive-vercel-index/blob/152380bd057d256bcd6cf3ececefcf5826fecaf9/components/previews/EPUBPreview.tsx#L59

这里是不是把odpt错写成了token?

**Comment by myl7** [comment]
确实应该是 `odpt`

如果方便的话你来发一个 PR？（既然是你发现的话）

**Comment by NekoMio** [comment]
> 确实应该是 `odpt`
> 
> 如果方便的话你来发一个 PR？（既然是你发现的话）

麻烦您啦～
