### ISSUE TITLE
密码功能无效

### ISSUE THREAD

**Issue by JeremyMin666** [spencerwooo/onedrive-vercel-index#67]
在config/site.json中定义了目录，在目录中加了.password.  还是可以直接打开文件夹不需要密码

**Comment by spencerwooo** [comment]
如何复现？请提供更详细的配置。

**Comment by JeremyMin666** [comment]
重新部署vercel后解决了！抱歉

**Comment by superen7527** [comment]
> 

你好，请问重新部署是删除Vercel项目重头重新设置一遍吗？还是哪个具体按钮？我以为和修改github配置一样每次会自动重新部署结果我这里好像没有效果是需要手动重新部署吗

**Comment by weekdaycare** [comment]
> > 
> 
> 你好，请问重新部署是删除Vercel项目重头重新设置一遍吗？还是哪个具体按钮？我以为和修改github配置一样每次会自动重新部署结果我这里好像没有效果是需要手动重新部署吗

![image](https://user-images.githubusercontent.com/63026074/175855728-a96c86b2-e972-4cc0-9511-cc448ffbe4fd.png)
这里的`redeploy`

**Comment by superen7527** [comment]
感谢

**Comment by superen7527** [comment]
> > > 
> > 
> > 
> > 你好，请问重新部署是删除Vercel项目重头重新设置一遍吗？还是哪个具体按钮？我以为和修改github配置一样每次会自动重新部署结果我这里好像没有效果是需要手动重新部署吗
> 
> ![image](https://user-images.githubusercontent.com/63026074/175855728-a96c86b2-e972-4cc0-9511-cc448ffbe4fd.png) 这里的`redeploy`

感谢
