### ISSUE TITLE
无法切换账户，即使已经替换另一个id和秘钥

### ISSUE THREAD

**Issue by sbmatch** [spencerwooo/onedrive-vercel-index#670]
```
许可证
Microsoft 365 E5 Developer (without Windows and Audio Conferencing)
```
即使按照wiki文档的要求也无法从个人账户切换E5账户，修改认证接口和驱动接口会进入一个密码认证的界面，但我没有要求加密任何目录  就像这样： [https://onedrive-vercel-index-b14pahbdl-3207754367.vercel.app/](https://onedrive-vercel-index-b14pahbdl-3207754367.vercel.app/)
```
Enter Password
This route (the folder itself and the files inside) is password protected. If you know the password, please enter it below.
```
不修改任何接口只修改 `client  ID` 与 `obfuscatedClientSecret` 至E5账户 ，界面没有任何改变，依旧是个人账户的onedrive·网盘内容

**Comment by myl7** [comment]
> 请问我该如何切换账户呢？

手动删除 Redis 数据库中的所有键值对，再重新进行认证即可。重新认证就是重新打开认证的那个 guide 网址。

**Comment by myl7** [comment]
> 但我没有要求加密任何目录 就像这样

这是因为你的 OneDrive 中对应文件夹下有一份名叫 `.password` 的文件。此文件存在时、通过 onedrive-vercel-index 访问此目录时，会提示输入密码，这个密码和 OneDrive 帐号密码没有关系。

**Comment by myl7** [comment]
> 不修改任何接口只修改 client ID 与 obfuscatedClientSecret 至E5账户

如果你没有进阶需求的话，无论使用任何 OneDrive 账户类型，都不需要修改这两个值。这两个值也与 OneDrive 帐号类型无关。
