### ISSUE TITLE
尝试将自定义404页面，但是似乎这并没有效果？

### ISSUE THREAD

**Issue by sbmatch** [spencerwooo/onedrive-vercel-index#672]
我尝试将自定义的404页提交至 /public 目录，并尝试期望得到自定义的404导航页，但这似乎没有任何效果？我该如何才能使自定义404页面生效

![404页面位于/public目录](https://pic.mpcloud.top/i/2022/06/03/6299b3174c6a1.png)

**Comment by myl7** [comment]
由于此项目使用了 Next.js 框架，如需自定义 404 界面，需要参照[文档](https://nextjs.org/docs/advanced-features/custom-error-page#404-page)进行自定义。
