### ISSUE TITLE
Application error: a client-side exception has occurred  用户侧错误

### ISSUE THREAD

**Issue by Lparksi** [spencerwooo/onedrive-vercel-index#675]
触发：在 https://pan.parksi.top/  中搜索 1
触发概率 100%
![image](https://user-images.githubusercontent.com/60086490/172498371-cdf6521f-3780-4304-964f-29ddbb6e0313.png)
![image](https://user-images.githubusercontent.com/60086490/172498408-bd38795b-0639-483a-b589-a3aa40a74758.png)

**Comment by V-Conet** [comment]
#539 可能有帮助

**Comment by shoucandanghehe** [comment]
#548 应该修复了这个问题
而且我注意到你fork的库似乎很久没有和主项目同步了
