### ISSUE TITLE
如何配置？

### ISSUE THREAD

**Issue by Thomitics** [spencerwooo/onedrive-vercel-index#7]
没找到配置client_secret和refresh_token的地方啊

**Comment by Revincx** [comment]
client_id在[/config/api.json](https://github.com/spencerwooo/onedrive-vercel-index/blob/main/config/api.json)里
cilent_secret和refresh_token在环境变量里。

**Comment by Thomitics** [comment]
> client_id在[/config/api.json](https://github.com/spencerwooo/onedrive-vercel-index/blob/main/config/api.json)里
> cilent_secret和refresh_token在环境变量里。

好的，谢谢！

**Comment by Thomitics** [comment]
> client_id在[/config/api.json](https://github.com/spencerwooo/onedrive-vercel-index/blob/main/config/api.json)里
> cilent_secret和refresh_token在环境变量里。

环境变量名字是什么呢？

**Comment by Revincx** [comment]
你看下(这一行)[https://github.com/spencerwooo/onedrive-vercel-index/blob/c1cdecae7ff88492c7612ff6199880fbd0849f34/pages/api/index.ts#L25]就知道了

**Comment by monsterxcn** [comment]
> > client_id在[/config/api.json](https://github.com/spencerwooo/onedrive-vercel-index/blob/main/config/api.json)里
> > cilent_secret和refresh_token在环境变量里。
> 
> 环境变量名字是什么呢？

`CLIENT_SECRET` `REFRESH_TOKEN`

**Comment by Revincx** [comment]
> > client_id在[/config/api.json](https://github.com/spencerwooo/onedrive-vercel-index/blob/main/config/api.json)里
> > cilent_secret和refresh_token在环境变量里。
> 
> 环境变量名字是什么呢？

你看下[这一行](https://github.com/spencerwooo/onedrive-vercel-index/blob/c1cdecae7ff88492c7612ff6199880fbd0849f34/pages/api/index.ts#L25)就知道了

**Comment by Thomitics** [comment]
> > > client_id在[/config/api.json](https://github.com/spencerwooo/onedrive-vercel-index/blob/main/config/api.json)里
> > > cilent_secret和refresh_token在环境变量里。
> > 
> > 
> > 环境变量名字是什么呢？
> 
> 你看下[这一行](https://github.com/spencerwooo/onedrive-vercel-index/blob/c1cdecae7ff88492c7612ff6199880fbd0849f34/pages/api/index.ts#L25)就知道了

嗯嗯……自己懒得看代码，所以就来问了，谢谢

**Comment by Thomitics** [comment]
> > > client_id在[/config/api.json](https://github.com/spencerwooo/onedrive-vercel-index/blob/main/config/api.json)里
> > > cilent_secret和refresh_token在环境变量里。
> > 
> > 
> > 环境变量名字是什么呢？
> 
> 你看下[这一行](https://github.com/spencerwooo/onedrive-vercel-index/blob/c1cdecae7ff88492c7612ff6199880fbd0849f34/pages/api/index.ts#L25)就知道了

可是配好了仍然Error: Request failed with status code 500
