### ISSUE TITLE
打开zh-CN等文件夹的小bug

### ISSUE THREAD

**Issue by V-Conet** [spencerwooo/onedrive-vercel-index#714]
在打开`zh-CN`, `zh-TW`等文件夹时, 无法显示文件夹内的内容, 而是从原语言变为所打开文件夹名称的语言

  下面是效果图
![](https://img1.imgtp.com/2022/07/23/8UmwRkz6.gif)

**Comment by spencerwooo** [comment]
由于 i18n 的考虑，特殊路径暂时不考虑做适配，除非我们全部更改路径的展现逻辑。（比如 base64 编码路径或用路径 ID 代替路径或者文件夹名称本身。）
