### ISSUE TITLE
Prepare for V1.0

### ISSUE THREAD

**Issue by spencerwooo** [spencerwooo/onedrive-vercel-index#72]
Reaching V1.0 milestone.

- [ ] New version, new README, new documentation
- [x] Polish up 404 page.

**Comment by HankMo** [comment]
Hello! I need the installation steps of the program and Chinese documents.

**Comment by HankMo** [comment]
I'd like to deploy your program on my own server, But I don't know where to start.

**Comment by spencerwooo** [comment]
> Hello! I need the installation steps of the program and Chinese documents.

Refer to [spencerwooo/onedrive-cf-index](https://github.com/spencerwooo/onedrive-cf-index) for now, stuff are basically the same.

**Comment by spencerwooo** [comment]
> I'd like to deploy your program on my own server, But I don't know where to start.

There's a Docker file for u to deploy with on your own server if that's what you are looking for BTW. https://github.com/spencerwooo/onedrive-vercel-index/discussions/112
