### ISSUE TITLE
能不能部署在cloudflare啊

### ISSUE THREAD

**Issue by kero990** [spencerwooo/onedrive-vercel-index#742]
能不能部署在cloudflare啊，我有大量的服务部署在cloudflare，所以不想再去vercel部署了，不过我在cloudflare构建失败，而且cloudflare只有一条构建命令的输入。请问有可能部署在cloudflare吗

**Comment by spencerwooo** [comment]
https://github.com/spencerwooo/onedrive-vercel-index/discussions/163
