### ISSUE TITLE
pdf 预览出错

### ISSUE THREAD

**Issue by dingeral** [spencerwooo/onedrive-vercel-index#75]
![截图_选择区域_20210901104148](https://user-images.githubusercontent.com/36292978/131603120-c1718649-8b62-4ca1-bbaf-cc6c9ee00e7e.png)

https://drive.dingeral.com/F1/%E8%BF%90%E5%8A%A8%E8%A1%8C%E4%B8%BA%E5%BF%97%E7%A0%94%E7%A9%B6_%E7%9F%AD%E8%B7%91%E6%8A%80%E6%9C%AF%E5%AE%9E%E8%B7%B5%E5%8F%99%E4%BA%8B%E2%80%94%E2%80%94%E8%8B%8F%E7%82%B3%E6%B7%BB%E4%B8%8E%E7%A8%8B%E5%BF%97%E7%90%86%E7%9A%84%E8%AE%AD%E7%BB%83%E5%AD%A6%E5%AF%B9%E8%AF%9D%E5%BD%95.pdf

**Comment by spencerwooo** [comment]
PDF 预览用的是 `pdf.js` 的 React 实现，如果标准库无法解决，我这里也无从无力。

**Comment by spencerwooo** [comment]
PDF preview for non-latin characters should be fixed with PR #186
