### ISSUE TITLE
Task timed out after 10.01 seconds

### ISSUE THREAD

**Issue by Ovler-Young** [spencerwooo/onedrive-vercel-index#759]
Task timed out after 10.01 seconds
![image](https://user-images.githubusercontent.com/44089074/187589902-51d2cb22-2103-486f-a195-a44c9f29da46.png)
在批量下载文件时，在vercel上出现该问题。同时，下载文件夹出现的压缩包中出现一大小仅为68B的文件，内容为
```
An error occurred with your deployment

FUNCTION_INVOCATION_TIMEOUT
```

**Comment by Ovler-Young** [comment]
`redis` 使用的是 `upstash` 的 `Pay as you go` plan.

**Comment by Ovler-Young** [comment]
在批量下载的时候有概率再次触发该错误，重试后能恢复正常

**Comment by spencerwooo** [comment]
Vercel 的限制了，项目这边无能为力。
