### ISSUE TITLE
歌曲MP3能否增加歌词和封面

### ISSUE THREAD

**Issue by sonrixmomo** [spencerwooo/onedrive-vercel-index#761]
在同目录加放封面图片.jpg/png.......
还有歌词.lrc

**Comment by spencerwooo** [comment]
同目录的操作不是规范或约定俗成的格式标准，无法进行进一步的支持。目前所有的歌曲、音频、视频的 metadata 均来自上游 API，也就是 OneDrive 服务器上对这些文件的分析。
