### ISSUE TITLE
建议：支持ASS字幕

### ISSUE THREAD

**Issue by BakaJzon** [spencerwooo/onedrive-vercel-index#762]
目前大部分番剧字幕组仅提供ASS字幕，能否添加字幕支持？

如
```
1. abc.mkv <内嵌>
2. xyz.mkv
2. xyz.ass
3. lmn.mkv
3. lmn.chs.ass
3. lmn.cht.ass
```
<https://onedrive.bakajzon.cf/zh-CN/Video/Anime>

**Comment by TragicLife** [comment]
目前仍有維護的專案只有 https://github.com/libass/JavascriptSubtitlesOctopus 實現了這個功能，而且和影片播放器整合暫時不夠好

**Comment by spencerwooo** [comment]
由于第三方对 ASS 格式字幕在 Web 浏览器上的支持较少，所以本项目暂时无法对 `.ass` 字幕文件进行支持。
