### ISSUE TITLE
字幕有办法调整大小吗

### ISSUE THREAD

**Issue by LongStudy** [spencerwooo/onedrive-vercel-index#765]
字幕有办法调整大小吗，番剧外挂字幕感觉比较小，如果能够调大一点就好了

**Comment by spencerwooo** [comment]
项目使用的视频播放器 Plyr 的字幕大小应该是这几个 CSS variable 定义的：

- `--plyr-font-size-base`
- `--plyr-font-size-small`
- `--plyr-font-size-large`
- `--plyr-font-size-xlarge`

详见：https://github.com/sampotts/plyr#customizing-the-css

**Comment by LongStudy** [comment]
十分感谢，在globals.css里添加上就OK了
