### ISSUE TITLE
请问程序如何以webdav或者alist的形式以数据源形式挂载视频播放器呢？

### ISSUE THREAD

**Issue by leftchest** [spencerwooo/onedrive-vercel-index#772]
请问程序如何以webdav或者alist的形式以数据源形式挂载至视频播放器呢？例如：tvbox视频软件：https://liucn.lanzouv.com/iCKjo0cmg1vi，菜单——文件下有挂载webdav和alist选项，我们的程序如何兼容可用此类软件挂载观看网盘视频呢?期待能得到指导，感谢

**Comment by spencerwooo** [comment]
没有安卓设备，我无法下载使用你说的 tvbox，既然软件直接适配了 alist，那么不如用 alist？
