### ISSUE TITLE
redis database  issue

### ISSUE THREAD

**Issue by sridhar885** [spencerwooo/onedrive-vercel-index#776]
![Screenshot (4)](https://user-images.githubusercontent.com/91075267/195408265-708d1472-a16b-4632-8f97-1a14164bf470.png)

hello sir sorry for opening the issue i dont understand the exact issue i have followed your guide for creating the index 
so from this pic what is the error, when i see the other issues in the project in the env section the logo of the upsplash is visible but in this its not visible is that the mistake and as this is not with tls encrypted its just redis://......

please provide me your telegram username for the further doubts if there is any 
thank you spencerwoo!! for creating this wooful projects

**Comment by sridhar885** [comment]
And for the MS E5 subscriptio we dont need to provide the client id and secrets rigt
thank you again

**Comment by sridhar885** [comment]
what is wrong with this is there any thing i need  to do why its like this

**Comment by therockstarind** [comment]
dm on telegram t.me/RockStarIND

> what is wrong with this is there any thing i need to do why its like this
