### ISSUE TITLE
希望可以支持反向代理

### ISSUE THREAD

**Issue by NAILIANGCHI** [spencerwooo/onedrive-vercel-index#782]
OneDrive国际版在线预览视频以及下载大文件是真慢大多数的时候，原本使用oneindex通过套cf来加速能实现加速下载。
希望作者后期更新可以考虑该功能

**Comment by spencerwooo** [comment]
早期尝试过使用 Vercel 直接进行反向代理，但是违反 Vercel fair use policy 无法下载超过 5Mb 的文件，项目尽量不准备引入除了 Vercel 外的服务，可以考虑自行用 Cloudflare 搭建。

**Comment by NAILIANGCHI** [comment]
您好！您的邮件我已经收到。阅读后尽快给您回复！
