### ISSUE TITLE
Not All videos are playable

### ISSUE THREAD

**Issue by Box-boi** [spencerwooo/onedrive-vercel-index#791]
- The videos in question would be found [here](https://boxdrive.vercel.app/Public/Anime).

- Some videos, for example [this](https://boxdrive.vercel.app/Public/Anime/Blend%20S%5BWATCHED%5D/) and [this](https://boxdrive.vercel.app/Public/Anime/Tokyo%20Revengers%5BWATCHED%5D/S1/) work fine.

- However, some videos like [this](https://boxdrive.vercel.app/Public/Anime/A%20Certain%20Magical%20Index/S1/) and [this](https://boxdrive.vercel.app/Public/Anime/Attack%20On%20Titan/S2/) don't load. Sometimes, there is a black screen and the video doesn't load(only audio works).

- I suspect it has something to do with encoding and/or codecs? could support for additional codecs be added?

**Comment by spencerwooo** [comment]
Not all video codec are supported in browsers. Check https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs
