### ISSUE TITLE
添加对 SharePoint 站点的支持.

### ISSUE THREAD

**Issue by cxplay** [spencerwooo/onedrive-vercel-index#817]
SharePoint 站点可以作为文档库以公开或私有的方式存放文件, 站点文档库也具有与 OneDrive 完全相同的功能, 有形如 `https://example.sharepoint.com/sites/example` 这样的唯一地址, 相比之下更适合多人管理, 希望能够添加支持.

**Comment by sridhar6564** [comment]
> SharePoint 站点可以作为文档库以公开或私有的方式存放文件, 站点文档库也具有与 OneDrive 完全相同的功能, 有形如 `https://example.sharepoint.com/sites/example` 这样的唯一地址, 相比之下更适合多人管理, 希望能够添加支持.

mee tooo need this feature did you get any update how to do this 
thanks in advance

**Comment by cxplay** [comment]
> > SharePoint 站点可以作为文档库以公开或私有的方式存放文件，站点文档库也具有与 OneDrive 完全相同的功能，有形如 `https://example.sharepoint.com/sites/example` 这样的唯一地址，相比之下更适合多人管理，希望能够添加支持.
> 
> mee tooo need this feature did you get any update how to do this thanks in advance

No

**Comment by sridhar6564** [comment]
> > > SharePoint 站点可以作为文档库以公开或私有的方式存放文件，站点文档库也具有与 OneDrive 完全相同的功能，有形如 `https://example.sharepoint.com/sites/example` 这样的唯一地址，相比之下更适合多人管理，希望能够添加支持.
> > 
> > 
> > mee tooo need this feature did you get any update how to do this thanks in advance
> 
> No

whether we need to change the directory in the site.config.js file  "/" means a public directory but is there any way we can add the shared files @spencerwooo

**Comment by sridhar6564** [comment]
like you have added the shared files 
https://drive.swo.moe/tr-TR/Shared%20files/ 
in this may i know how to add
 baseDirectory: '/',
 in this

**Comment by Rigolino1** [comment]
> like you have added the shared files
> https://drive.swo.moe/tr-TR/Shared%20files/
> in this may i know how to add
> baseDirectory: '/',
> in this @spencerwooo

bro you can fix that?

**Comment by doomwithdon** [comment]
I would like this feature too please

**Comment by doomwithdon** [comment]
I managed to get this working for sharepoint. You just need to update api config with the correct driveApi config for the sharepoint site

**Comment by spencerwooo** [comment]
Seems that by changing the `driveApi` to adapt SharePoint endpoints would solve this. Closing for now.

**Comment by wx69wx** [comment]
1.存储token前driveapi必须为https://graph.microsoft.com/v1.0/me/drive，否则会提示不是网站所有者
2.帖子里已经说得很详细了，通过访问 https://xxxx.sharepoint.com/sites/test20230412/_api/web/id 获得siteid (假设站点名为test20230412，xxxx是你onmicrosoft.com前面部分)
siteid是一串字符，从你的帖子看应该是22358628-xxxx-xxxx2d2f
所以driveapi应该为 https://graph.microsoft.com/v1.0/sites/22358628-xxxx-xxx2d2f/drive

**Comment by wx69wx** [comment]
补充一下，如果你没有新建子site，而是直接使用最上层的comunication site的文档，则siteid通过访问https://xxxx.sharepoint.com/_api/site/id得到

**Comment by yiranxiamo** [comment]
> 补充一下，如果你没有新建子site，而是直接使用最上层的comunication site的文档，则siteid通过访问[https://xxxx.sharepoint.com/_api/site/id得到](https://xxxx.sharepoint.com/_api/site/id%E5%BE%97%E5%88%B0)

大佬看下
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata">
<m:code>-2147024891, System.UnauthorizedAccessException</m:code>
<m:message xml:lang="zh-CN">Attempted to perform an unauthorized operation.</m:message>
</m:error>

**Comment by yiranxiamo** [comment]
> 1.存储token前driveapi必须为[https://graph.microsoft.com/v1.0/me/drive，否则会提示不是网站所有者](https://graph.microsoft.com/v1.0/me/drive%EF%BC%8C%E5%90%A6%E5%88%99%E4%BC%9A%E6%8F%90%E7%A4%BA%E4%B8%8D%E6%98%AF%E7%BD%91%E7%AB%99%E6%89%80%E6%9C%89%E8%80%85) 2.帖子里已经说得很详细了，通过访问 https://xxxx.sharepoint.com/sites/test20230412/_api/web/id 获得siteid (假设站点名为test20230412，xxxx是你onmicrosoft.com前面部分) siteid是一串字符，从你的帖子看应该是22358628-xxxx-xxxx2d2f 所以driveapi应该为 https://graph.microsoft.com/v1.0/sites/22358628-xxxx-xxx2d2f/drive

大佬帮我检查一下，我使用全局管理重新创建了site，重新部署了一次。
（挂载OneDrive没问题）
https://github.com/yiranxiamo/OneDrive-vercel-index/tree/main/config

**Comment by wx69wx** [comment]
我是E5账户没问题，世纪互联账户请根据说明修改authapi.
关于siteid获取提示无授权，请先访问https://yoxvalleypartnership.sharepoint.com登录成功后，再访问https://yoxvalleypartnership.sharepoint.com/sites/mediy/_api/web/id
或者https://yoxvalleypartnership.sharepoint.com/_api/site/id

得到子站点mediy或主站点的siteid

另外提醒下，必须先https://graph.microsoft.com/v1.0/me/drive，否则token存储会提示不是网站所有者，存储token成功后，再修改driveapi为siteid的，重新部署即可

**Comment by yiranxiamo** [comment]
> 
非常感谢你的指点，挂载SharePoint终于成功了。
分享给其他新手。
重点就是，一定要先用 https://graph.microsoft.com/v1.0/me/drive 来存储token，存储成功之后，在把这个链接改为如下，之后再次部署即可。
driveApi 格式：https://graph.microsoft.com/v1.0/sites/{siteid}/drive
siteid可以用rclone，也可以用楼主的方法来获取。
链接示例：（其中xxxxxx是您的域）
https://graph.microsoft.com/v1.0/sites/xxxxxx.sharepoint.com,6288550a-f76e-4e34-96c3-2ab6efcb76aa,22358628-2e53-4e06-b9b6-5dde15e52d2f/drive

**Comment by lzhxwmr** [comment]
[Official Doc](https://learn.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-1.0#note-for-existing-sharepoint-developers) FYI
