### ISSUE TITLE
希望可以新增文件上传功能

### ISSUE THREAD

**Issue by kasisama** [spencerwooo/onedrive-vercel-index#823]
如果有文件上传功能的话，我感觉真的就很完美了qwq

**Comment by wdw1007** [comment]
#453 有相关议题
并且开发者在 https://github.com/spencerwooo/onedrive-vercel-index/discussions/126 (讨论不知道为啥没了) 表示过不会支持上传

**Comment by spencerwooo** [comment]
> 讨论不知道为啥没了

可能是被之前提的人删掉了，我这边应该是没动过。

> 如果有文件上传功能的话

确实暂时不在此版考虑范围内，因为认证涉及到对当前 secret 文件夹乃至整个项目的鉴权问题。
