### ISSUE TITLE
似乎不支持Font Awesome v6才新增的图标?

### ISSUE THREAD

**Issue by Master-in** [spencerwooo/onedrive-vercel-index#831]
Font Awesome v6之前就有的图标能够正常显示，v6才新增的图标无法正常显示

**Comment by Zhousiru** [comment]
遇到相同问题，已经自行升级解决
Font Awesome v6 需要一些特别操作才能与 SSR 兼容
可以参考 [这个 Commit](https://github.com/Zhousiru/onedrive-vercel-index-mod/commit/87c91f37e42900f835297888c68f0ef0233b08be) 和 [这个 Issue](https://github.com/FortAwesome/Font-Awesome/issues/19348)

**Comment by spencerwooo** [comment]
@Zhousiru 谢谢提到的升级方案 ;) (Ref #835 )
