### ISSUE TITLE
账号token in ENV

### ISSUE THREAD

**Issue by BakaJzon** [spencerwooo/onedrive-vercel-index#853]
**Is your feature request related to a problem? Please describe.**
Upstash 免费版仅提供一个 redis 库，多个redis库要收费。

**Describe the solution you'd like**
似乎项目用到redis的部分只有 `refresh_token` 的获取，能否提供一个可选项，使用vercel环境变量直接写入同一账号的令牌。

**Describe alternatives you've considered**
Something like that:
`refresh_token = env.USER_REFRESH_TOKEN || getFromRedis(xxx)`

**Comment by ICE99125** [comment]
refresh_token 不是会更新的嘛? 不能写死的吧

**Comment by spencerwooo** [comment]
已有解决方案了，参考：https://github.com/spencerwooo/onedrive-vercel-index/pull/572

**Comment by BakaJzon** [comment]
@spencerwooo 文档里能不能加上这个 #572 用法呢
