### ISSUE TITLE
Zip download

### ISSUE THREAD

**Issue by Itz-Ayanokoji** [spencerwooo/onedrive-vercel-index#879]
Recently I uploaded hundreds one photos in onedrive and I wanted to download them altogether but there isn't any option to download all together

Like onedrive provides a features for download many files in the form of zip. The index should also provide to make them useful

I request you to provide a feature for zip downloading for more than 5 files in a folder.

**Comment by spencerwooo** [comment]
**_You are not using the issue template for feature requests._**

Anyway, this feature is already present. You can already select and download a batch of zipped files.
