### ISSUE TITLE
文件名过长，显示不出来

### ISSUE THREAD

**Issue by tkfanswind** [spencerwooo/onedrive-vercel-index#883]
文件名过长，显示不出来，请问如何解决？

**Comment by tkfanswind** [comment]
修改哪个配置文件能让文件名那列宽点嘛？

**Comment by spencerwooo** [comment]
你可能得直接去源代码里面修改。特别的，这一部分渲染文件列表各个项目：

https://github.com/spencerwooo/onedrive-vercel-index/blob/4c0e399e915e765a4bbfc8d467a4dd0eb68c6c47/src/components/FolderListLayout.tsx#L15-L32

**Comment by tkfanswind** [comment]
<div className="col-span-3 hidden flex-shrink-0 font-mono text-sm text-gray-700 dark:text-gray-500 md:block"> 
      <div className="col-span-1 hidden flex-shrink-0 truncate font-mono text-sm text-gray-700 dark:text-gray-500 md:block"> 

是修改这两行吗？这两行的4个数代表啥意思？
