### ISSUE TITLE
部署完之后显示404错误

### ISSUE THREAD

**Issue by sdlkhfksl** [spencerwooo/onedrive-vercel-index#885]
{"error":{"error":{"code":"itemNotFound","message":"Item does not exist","innerError":{"date":"2023-02-21T02:05:57","request-id":"badd5f5f-6faf-4f05-9ba4-19a9d56a72d5","client-request-id":"badd5f5f-6faf-4f05-9ba4-19a9d56a72d5"}}}}

**Comment by spencerwooo** [comment]
Please check: https://ovi.swo.moe/docs/getting-started#customise-site-settings

Make sure `baseDirectory` actually exists inside your drive.
