### ISSUE TITLE
Wrong File Extension

### ISSUE THREAD

**Issue by od-i** [spencerwooo/onedrive-vercel-index#901]
Hi,

when ever i try to download from index using Neat Download Manager its give me wrong 
file extension or duplicated for example
if i download mp4 file it rename to .mp4.mp4
and for mkv its getting rename to .mkv.aspx
here screenshot
![Untitled](https://user-images.githubusercontent.com/126561953/222934691-b23f0d1a-7597-4c97-b25a-fd6efb3b1c3f.png)

**Comment by spencerwooo** [comment]
If Chrome is parsing the file information correctly, then this should be your download manager's issue, unfortunately.

**_Also, you are not using the issue template._**
