### ISSUE TITLE
Suggest to support previous and next picture when previewing

### ISSUE THREAD

**Issue by muxinxy** [spencerwooo/onedrive-vercel-index#925]
When previewing images, there are buttons at the bottom for previous and next images, making it easy to switch between images without having to go back and click on another image. Or there is a drop-down list above to select other images.

预览图片时，下方有上一张和下一张的按钮，方便切换图片，不用返回再点击其他图片。或者上方有一个下拉列表能够选择其他图片。

**Comment by spencerwooo** [comment]
之前由于性能问题，抛弃了你说的这种图片预览方式，使用 grid 视图实现的图片预览。
