### ISSUE TITLE
修改.password文件后报500错误

### ISSUE THREAD

**Issue by Montaro2017** [spencerwooo/onedrive-vercel-index#93]
原本已经设置好了密码，添加了密码保护路由，进去需要输入密码才能访问，但是之后我i修改了.password文件后清除cookie和localStorage再访问报500错误，修改为以前的密码就没问题

**Comment by spencerwooo** [comment]
这边没成功复现，更换 .password 文件内容后一切如预期，有更详细的 bug 复现方法吗？

**Comment by Montaro2017** [comment]
> 这边没成功复现，更换 .password 文件内容后一切如预期，有更详细的 bug 复现方法吗？

我是先添加了密码保护路由然后在添加的.password文件，我刚刚又试了一下，新建了个密码保护的文件夹，直接500错误了
这是我添加的位置 密码是123456  https://i.montaro.cn/%E2%9A%BD%20%E6%B8%B8%E6%88%8F%20-%20Game/%E5%AF%86%E7%A0%81%E4%BF%9D%E6%8A%A4%E6%B5%8B%E8%AF%95

**Comment by opoet** [comment]
我这边也遇到了这个问题

**Comment by opoet** [comment]
目前貌似已经不存在这个bug了，我重复了我之前的步骤，但是未能复现
