### ISSUE TITLE
存储token 时提示“你不是网站所有者”

### ISSUE THREAD

**Issue by wx69wx** [spencerwooo/onedrive-vercel-index#952]
**Describe the bug**
存储token 时提示“你不是网站所有者”

**To Reproduce**
2. Run '....'
3. See error

**Expected behavior**

**Screenshots**

**Additional context**
确认环境变量redis_url填写正确，redis密码没错，可以用python 测试访问数据库正常

**Comment by wx69wx** [comment]
可以了，是因为我是E5用户，文档是在sharepint下某个site的，所以之前把 driveApi: 'https://graph.microsoft.com/v1.0/me/drive' 改成了 driveApi: 'https://graph.microsoft.com/v1.0/sites/{siteid}/drive' , 导致了问题，先改回me/drive 存储token就没问题了，然后再改成sites/{siteid}/drive， 访问正常。

非常感谢大佬的项目！

**Comment by spencerwooo** [comment]
👍 很开心问题得到解决。提示「你不是网站所有者」主要是由于在校验你用来认证的 email 和你在配置文件里设置的是否一致，保证是你自己存储的 token。
