### ISSUE TITLE
Search not working on video files.

### ISSUE THREAD

**Issue by coderxtg** [spencerwooo/onedrive-vercel-index#971]
If i search a video in the index then it show nothing here.

You can see that i have some video files.
![image](https://user-images.githubusercontent.com/132077045/235347868-12f359c3-1f8f-4303-8647-0af9daa119f9.png)

Now when i search them, It show "nothing here" 
![image](https://user-images.githubusercontent.com/132077045/235347916-a532a36a-9087-4390-ac10-ad05b903c061.png)

**Comment by spencerwooo** [comment]
You would need some time for OneDrive to process the changes and update the search index. Anyhow, search is powered by the upstream OneDrive API, which is outside the scope of this project. :(
