### ISSUE TITLE
Hide the Download button of folders

### ISSUE THREAD

**Issue by yhd12138** [spencerwooo/onedrive-vercel-index#997]
How do I hide the **Download button** of any folders? Any help is appreciated.

**Comment by therockstarind** [comment]
> How do I hide the **Download button** of any folders? Any help is appreciated.

can you explain little bit??

**Comment by therockstarind** [comment]
add me to your repo

**Comment by yhd12138** [comment]
> add me to your repo

Thanks, I think I have managed to hide it.
